libs/ui/icon/helm/src/lib/hlm-icon.component.spec.ts
libs/ui/icon/helm/src/lib/hlm-icon.component.ts
libs/ui/icon/icon.stories.ts
package.json

- Icon no longer passes sizes & classes to ng-icon but applies to self. Added semantic sizes (xSmall - xLarge) & added support for tailwinds sizes (h-6, w-6 etc.)
- Commitlint windows support (removed $1 from package.json) 
Closes #
any icon implementations using size need to change to one of new options or use tailwind classes to size their icons

Feature(icon): support tailwind and semantic sizes

---

apps/app/src/app/pages/(home).page.ts

When Im opening [spartan.ng](https://www.spartan.ng/) on mobile first what I see are not properly alignment buttons.
Closes #
The button's are now properly aligment on mobile screen's (desktop does not change).

(docs): fix home page buttons alignment on mobile screens

---

libs/ui/menu/brain/src/lib/brn-menu-item-radio.directive.ts

BrnMenuItemRadio incorrectly uses CdkMenuItemcheckbox
Closes #
Use CdkMenuItemRadio instead

use cdkMenuItemRadio in BrnMenuItemRadio directive

---

apps/app/src/app/pages/(stack)/stack/(technologies)/technologies.page.ts

Found one more typo, I searched through the whole docs-Folder now. Should be the last one.

docs: fix title of spartan/stack technologies page

---

libs/nx/src/generators/ui/libs/ui-input-helm/files/lib/hlm-input.directive.ts.template
libs/nx/src/generators/ui/libs/ui-label-helm/files/lib/hlm-label.directive.ts.template
libs/ui/input/helm/package.json
libs/ui/input/helm/src/lib/hlm-input.directive.ts
libs/ui/input/input.stories.ts
libs/ui/label/helm/src/lib/hlm-label.directive.ts
libs/ui/label/label.stories.ts

I was wondering about integrating Input with Reactive Forms when it comes to presenting the error state - in my opinion, since the library is being created for Angular, it is worth considering. I am presenting the initial concept, you can safely ignore it if you don't like it, it is basically not so much a ready PR as a POC solution - maybe it's just worth discussing. See if you see such a solution in your project.
Input for the `error` state and integration with NgControl which allows for self-management of the components error state.

feat(input): input / label error self management

---

libs/ui/icon/helm/src/lib/hlm-icon.component.spec.ts
libs/ui/icon/helm/src/lib/hlm-icon.component.ts

The classes of the Hostbinding where not set correctly for onPush Hosts. The size was not displayed correctly.
Now the classes of the icon are set and detected by the host correctly.
close #46
icon
The classes of the Hostbinding are not set correctly for onPush Hosts. The size of the icon was not displayed correctly.
Closes #46 
Now the classes of the icon are set and detected by the host correctly.

fix(icon): fix HostBinding classes for onPush Host

---

libs/ui/avatar/brain/src/lib/fallback/brn-avatar-fallback.directive.ts
libs/ui/avatar/helm/src/lib/fallback/hlm-avatar-fallback.directive.spec.ts
libs/ui/avatar/helm/src/lib/fallback/hlm-avatar-fallback.directive.ts
libs/ui/icon/helm/src/lib/hlm-icon.component.ts

icon
generateclasses was called on the setter
Closes #
now the host class is set by a computed

refactor: icon bind to host in decorator

---

libs/nx/src/generators/ui/libs/ui-command-helm/files/lib/hlm-command-dialog.directive.ts.template
libs/nx/src/generators/ui/libs/ui-dialog-helm/files/lib/hlm-dialog-content.directive.ts.template
libs/nx/src/generators/ui/libs/ui-hover-card-helm/files/lib/hlm-hover-card-content.directive.ts.template
libs/nx/src/generators/ui/libs/ui-popover-helm/files/lib/hlm-popover-content.directive.ts.template
libs/nx/src/generators/ui/libs/ui-sheet-helm/files/lib/hlm-sheet-content.directive.ts.template
libs/ui/accordion/brain/src/lib/brn-accordion-content.component.ts
libs/ui/accordion/brain/src/lib/brn-accordion-trigger.component.ts
libs/ui/alert-dialog/brain/src/lib/brn-alert-dialog-content.directive.ts
libs/ui/alert-dialog/brain/src/lib/brn-alert-dialog-overlay.component.ts
libs/ui/command/helm/src/lib/hlm-command-dialog.directive.ts
libs/ui/core/src/lib/brain/create-injection-token.ts
libs/ui/core/src/lib/brain/custom-element-class-settable.ts
libs/ui/core/src/lib/brain/exposes-side.ts
libs/ui/core/src/lib/brain/exposes-state.ts
libs/ui/core/src/lib/brain/table-classes-settable.ts
libs/ui/dialog/brain/src/lib/brn-dialog-content.directive.ts
libs/ui/dialog/brain/src/lib/brn-dialog-overlay.component.ts
libs/ui/dialog/helm/src/lib/hlm-dialog-content.directive.ts
libs/ui/hover-card/brain/src/lib/brn-hover-card-content.directive.ts
libs/ui/hover-card/helm/src/lib/hlm-hover-card-content.directive.ts
libs/ui/popover/brain/src/lib/brn-popover-content.directive.ts
libs/ui/popover/helm/src/lib/hlm-popover-content.directive.ts
libs/ui/sheet/brain/src/lib/brn-sheet-content.directive.ts
libs/ui/sheet/brain/src/lib/brn-sheet-overlay.component.ts
libs/ui/sheet/helm/src/lib/hlm-sheet-content.directive.ts
libs/ui/table/brain/src/lib/brn-table.component.ts

This PR adds `createInjectionToken` function to abstract the way we create `InjectionToken`
- `InjectFn` is strongly-typed and has overloads to properly support `{optional: true}`
- `ProvideFn` is strongly-typed version of `{provide, useValue}`
- `ProvideFnExisting` is strongly-typed version of `{provide, useExisting}`
- `TOKEN` is exposed for more manual use-cases
Currently, the `InjectionToken` inside of `ui-core` is created manually, and the exposed `inject***()` does not support `{ optional: true }` properly, leading to various places using Optional Chaining unnecessarily. 
Closes …

fix: abstract injection token creation

---

libs/ui/command/brain/package.json
package.json
yarn.lock

The current peerDependency @ngneat/cmdk is set to version 1.0.1 which is depends on Angular v15
This PR should fix complaining about peer dependencies when using command module.

chore(command):  bump dependency @ngneat/cmdk version

---

apps/ui-storybook-e2e/src/integration/accordion/accordion.cy.ts
libs/ui/accordion/accordion.stories.ts
libs/ui/accordion/brain/src/lib/brn-accordion-trigger.directive.ts
libs/ui/accordion/brain/src/lib/brn-accordion.directive.ts

When 2 accordions are on the app, the arrowkeys of the focusmanager stops working. This can be seen on spartan.ng.
When switching from `Documentation` to `Accordion` the accordion ArrowDown does not work.
This ist because the id is used to set the activeElement-index of the Focusmanager, which is not correct.
Closes #
The `ArrowDown` now selects the next Trigger. The Focusmanager is set by the Item instead of the Item.id.
Instead of document.activeElement we now use the FocusMonitor to determine if the accordion is focused.

Arrow Keys do not work when multiple accordions are present

---

libs/ui/sheet/helm/src/index.ts

The HlmSheetHeaderComponent cannot be resolved when importing HlmSheetModule.
Closes #76
The HlmSheetHeaderComponent is exported by the HlmSheetModule.

fix(sheet): the HlmSheetModule exports HlmSheetHeadercomponent

---

apps/app/src/app/pages/(components)/components/(combobox)/combobox.preview.ts
libs/ui/combobox/combobox.stories.ts
libs/ui/dialog/brain/src/lib/brn-dialog.component.ts

@dongphuong0905 I made the changes to fix this in the examples. The issue is that we are using a signal state() to control the state of the dialog from the outside. However, the brnDialogTrigger sets the state automatically on the inside when clicked... we therefore have to manually update the state to open when the trigger is clicked to stay in sync!
I am closing https://github.com/goetzrobin/spartan/pull/80 in favor of this PR! Thanks for your commit and bringing this to my attention!

fix(combobox): dialog should be closed after selecting the item

---

libs/ui/tooltip/helm/src/lib/hlm-tooltip-trigger.directive.ts

side of before and after is translated to left and right accordingly to direction. Nothing to do here, because it already works as intended with left and right.
A Todo comment is in the source to fix rtl direction animation slide in of the tooltip
The Todo is removed, because it is nothing to do.
Also the `data-[side=after]` and `data-[side=before]` are removed, as they are translated to left and right.

refactor(tooltip): remove side before and after slide classes

---

README.md

I think the README.md referenced a wrong library name.
Closes #

docs(nx): replace out of date library name in the readme

---

libs/ui/sheet/brain/src/lib/brn-sheet-trigger.directive.ts

Opening the sheet will trigger twice, since we define the host element bindings in the sheet itself and also inherited it from the dialog.
Closes #102
Host element bindings got removed and instead only inherited it from the dialog.

fix(sheet): prevent sheet from triggering twice

---

libs/cli/src/generators/ui/generator.ts

The generator prompts the user when a primitive depends on the icon or button primitives. This happens even if the icon/button primitives were part of the selection.
If the user selected the icon/button primitives the prompt is skipped.

fix(cli): skip prompts if dependencies already selected

---

libs/ui/storybook/.storybook/main.js
libs/ui/storybook/.storybook/preview.js
libs/ui/storybook/project.json

Storybook configuration
Currently within storybook not able to add styles in component decorator without receiving an error similar to the below image when trying to add something like the following in a component:
```
@Component({
...
styles: [
`
:host {
display: flex;
box-sizing: border-box;
flex-direction: column;
outline: none;
pointer-events: auto;
}
`,
],
...
})
```
Discovered it is a config issue related @storybook/addon-styling which does not allow us to use any of the addon options when using angular. They mention this issue here …

fix: storybook error when adding decorator styles

---

apps/app/src/app/pages/(components)/components/(tabs)/tabs--vertical.preview.ts
apps/app/src/app/pages/(components)/components/(tabs)/tabs.preview.ts
libs/cli/src/generators/ui/libs/ui-tabs-helm/files/index.ts.template
libs/cli/src/generators/ui/libs/ui-tabs-helm/files/lib/hlm-tabs.component.ts.template
libs/ui/tabs/helm/src/index.ts
libs/ui/tabs/helm/src/lib/hlm-tabs.component.ts
libs/ui/tabs/tabs.stories.ts

* update tabs code examples to only use hlm tabs
User need to use `BrnTabsDirective` in the template.
```html
<div brnTabs="account">
...
</div>
```
Exposes a `HlmTabsComponent` to be used instead of `BrnTabsDirective`. `HlmTabsComponent` has `BrnTabsDirective` as host directive and exposes all inputs. Active tab is provided with `tab` input.
```html
<hlm-tabs tab="account">
...
</hlm-tabs>
```
I have updated the tabs examples to only use `HlmTabs*` imports.

feat(tabs): expose hlm-tabs component

---

apps/app/src/app/pages/(components)/components/(accordion)/accordion--multiple-opened.example.ts
apps/app/src/app/pages/(components)/components/(accordion)/accordion.page.ts
apps/ui-storybook-e2e/src/integration/accordion/accordion.cy.ts
libs/ui/accordion/accordion.stories.ts
libs/ui/accordion/brain/src/lib/brn-accordion-item.directive.ts
libs/ui/accordion/brain/src/lib/brn-accordion.directive.ts
libs/ui/accordion/helm/src/lib/hlm-accordion-item.directive.ts
libs/ui/accordion/helm/src/lib/hlm-accordion.directive.ts

The open state is not controllable from outside. 
Closes #144 
With the new property isOpened in the brnAccordionItemDirective and hlmAccordionItemDirective it is possible to set the open state from outside.

feat(accordion): initial open stat can be set

---

libs/ui/tabs/brain/src/lib/brn-tabs-content.directive.ts
libs/ui/tabs/brain/src/lib/brn-tabs-trigger.directive.ts
libs/ui/tabs/brain/src/lib/brn-tabs.directive.ts
libs/ui/tabs/helm/src/lib/hlm-tabs-content.directive.ts
libs/ui/tabs/helm/src/lib/hlm-tabs-list.component.ts
libs/ui/tabs/helm/src/lib/hlm-tabs-trigger.directive.ts
libs/ui/tabs/helm/src/lib/hlm-tabs.component.ts
libs/ui/tabs/tabs.stories.ts

* pass disabled prop correctly from hlmTabsTrigger to brnTabsTrigger
* change _userClass to public, vscode shows errors for class in template otherwise
Using input signal where possible. Also passing `disabled` prop correctly from hlmTabsTrigger to brnTabsTrigger.

refactor(tabs): use input signals

---

libs/ui/table/brain/src/lib/brn-column-manager.spec.ts
libs/ui/table/brain/src/lib/brn-column-manager.ts

Closes #182 
`BrnColumnManager.allColumns` correctly returns an array of strings if initialized with a `Record<string,boolean>`
It fixes an unexpected breaking change that was introduced in 336

fix(table): allColumns in column manager returns unexpected array of objects

---

libs/cli/src/generators/ui/libs/ui-select-helm/files/lib/hlm-select-label.directive.ts.template
libs/cli/src/generators/ui/libs/ui-select-helm/files/lib/hlm-select-option.component.ts.template
libs/cli/src/generators/ui/libs/ui-select-helm/files/lib/hlm-select-trigger.component.ts.template
libs/ui/select/helm/src/lib/hlm-select-label.directive.ts
libs/ui/select/helm/src/lib/hlm-select-option.component.ts
libs/ui/select/helm/src/lib/hlm-select-trigger.component.ts

Select defaults to 'New York' style instead of the default shadcn style.
Closes #166 
Select will follow the "default", inline with the rest of the library currently

fix(select): updates select to default styling

---

libs/ui/checkbox/brain/src/lib/brn-checkbox.component.ts
libs/ui/checkbox/helm/src/lib/hlm-checkbox-checkicon.component.ts
libs/ui/checkbox/helm/src/lib/hlm-checkbox.component.ts

- Refactoring to use input signals
- Fix margin styles in brn-checkbox
- Apply additional attributes from hlm-checkbox to brn-checkbox (name, required, aria-*)
- Apply required attribute to checkbox input
- Simplify id/name for child and compute for host

refactor: input signals for checkbox and small improvements

---

libs/cli/src/generators/ui/libs/ui-checkbox-helm/files/lib/hlm-checkbox-checkicon.component.ts.template
libs/ui/checkbox/helm/src/lib/hlm-checkbox-checkicon.component.ts
libs/ui/hover-card/helm/src/lib/hlm-hover-card-content.component.ts

A private input that was never set was used for hlm() instead of userClass().
Closes #
userClass() is now used as in other components.

fix(hover-card): userclass input is set with hlm. remove TODO

---

apps/app/src/app/pages/(documentation)/documentation/(ui)/installation.page.ts
apps/app/src/app/shared/code/code.component.ts
apps/app/src/app/shared/layout/tabs-cli.component.ts

Tailwind  configuration is shown ugly in one line. Not readable.
Closes #
Tailwind configuration is now readable.
Before
After

docs: show tailwind configuration in multiline code

---

apps/ui-storybook-e2e/src/integration/select/select.cy.ts
libs/ui/select/select.stories.ts

fixed typo initalValue. --> initialValue
The initialValue is not set in storybook. 
Closes #220 
When providing a initialValue for the ```NgModelFormControl``` the value is set as ngModel in the select story.

fix(select): ngModel story uses initialValue

---

libs/ui/select/brain/src/lib/brn-select-content.component.ts
libs/ui/select/brain/src/lib/brn-select.component.ts
libs/ui/select/brain/src/lib/brn-select.service.ts
libs/ui/select/brain/src/lib/tests/brn-select.component.numbers.spec.ts

multiple selections are not cleared after selecting additional option
The value bound to [(ngModel)] is not displayed correctly in the control if it is not a string or a array.
When multiple is true and a value is provided via ngModel
When then addtional option is selected, the first options are not checked anymore.
In this example, 1,3 are preselected by ngModel and 4 was clicked.
Closes #237 
Values set by ngModel are set correctly also when it is a number.
For multiple Select, the initialValues are set always when the Value changes from the ControlValueAccessor, because otherwise, …

fix(select): ngModel values are displayed

---

apps/app/src/app/pages/(components)/components/(command)/command.page.ts
apps/app/src/app/pages/(documentation)/documentation/about.page.ts

- The docs mention the ngneat/cmdk package, but the package has been changed to ngxpert/cmdk.
- Links to the docs of ngxpert/cmdk are broken, because they still point to their old domain.
Closes #243
- ngneat/cmdk references in the documentation have been changed to ngxpert/cmdk.
- Links to the docs of ngxpert/cmdk point to their new domain.

docs: change ngneat/cmdk to ngxpert/cmdk

---

apps/ui-storybook-e2e/src/integration/select/select.cy.ts
libs/ui/select/brain/src/lib/brn-select-option.directive.ts
libs/ui/select/brain/src/lib/brn-select.service.ts
libs/ui/select/select.stories.ts

When options are provided via an array in a @for loop. The initial value is not set when provided with an formcontrol.
Closes #282 
The initial value is displayed correctly.
The value was set via writevalue before the options were registered, therefore the value was ignored.

fix(select): initialvalue is recognized when provided with formcontrol

---

libs/ui/select/brain/src/lib/brn-select.component.ts
libs/ui/select/brain/src/lib/tests/brn-select.component.numbers.spec.ts

value bound to ngModel was "null" when the 0 Value was selected
Closes #292 
value bound to ngModel is 0 when the 0 Value is selected.

fix(select): don't treat 0 value as null

---

libs/ui/select/brain/src/lib/brn-select.component.ts
libs/ui/select/brain/src/lib/tests/brn-select.component.spec.ts
libs/ui/select/brain/src/lib/tests/select-multi-mode.spec.ts
libs/ui/select/brain/src/lib/tests/select-ng-model-form.ts
libs/ui/select/brain/src/lib/tests/select-reactive-form.ts
libs/ui/select/brain/src/lib/tests/select-single-mode.spec.ts
libs/ui/select/brain/src/lib/tests/utils.ts
libs/ui/select/select.stories.ts

Currently just adds more test related to select's form control
Closes #224

fix: select form control status dirtied on initial value and patchValue

---

apps/app/src/app/pages/(home)/components/three-hundred.component.ts
libs/ui/select/brain/src/lib/brn-select-option.directive.ts
libs/ui/select/brain/src/lib/brn-select.component.ts
libs/ui/select/brain/src/lib/tests/select-reactive-form.ts
libs/ui/select/brain/src/lib/tests/select-single-mode.spec.ts

When we set the form value asynchronously the select won't respond to the first selection from the user (the form value won't be updated)
Closes #303 
Synchronously updating the form value doesn't break the initial selection from the user.

fix: set shouldEmitValueChange to true on user change event for select

---

apps/app/src/app/pages/(home)/components/th-item.component.ts
apps/app/src/app/pages/(home)/components/three-hundred.component.ts

[DOCUMENTATION] add github avatar to the 300 contributors

---

libs/ui/checkbox/checkbox.stories.ts

Closes #
While checking the stories for checkbox, I found this weird text `/* HTML */` on top of labels of checkbox. Which I believe should have been comments. Hence, thought of moving the supposedly comments to their correct places.

refactor(checkbox): remove `/*HTML*/` within story template strings

---

apps/app/src/app/pages/(documentation)/documentation/(ui)/(typography)/typography.preview.ts

The package name was incorrect. It should have included 'ui'
https://github.com/goetzrobin/spartan/issues/336
Closes #
The behavior remains unchanged. I only updated the imports of the various components inside the `typography.component.ts` file.

docs: update wrong import typography helm

---

libs/ui/avatar/brain/src/lib/image/brn-avatar-image.directive.ts

Closes https://github.com/goetzrobin/spartan/issues/338
I've encountered the same issue while loading async data for my POC. I still need to test more usecase in case the `@HostListener('load')` isn't reliable enough.
Credits to @ajitzero and @jackyshows

fix(avatar): properly handle invalid url status

---

libs/ui/core/package.json
package.json
pnpm-lock.yaml

Changelog can be found here:
https://github.com/lukeed/clsx/releases

chore: bump clsx

---

apps/app/src/app/pages/(components)/components/(context-menu)/context-menu-with-state.preview.ts
apps/app/src/app/pages/(components)/components/(context-menu)/context-menu.page.ts
libs/ui/menu/brain/src/lib/brn-context-menu-trigger.directive.ts

Currently, you can't pass any data to context-menu
This feature allows you to pass data to a context menu template. 
Data is passed through to the `ngTemplateOutletContext` by setting the `brnCtxMenuTriggerData` directive input so data will be available using the `let-` keyword in the scope of the template

feat(context-menu): pass data to menu

---

apps/app/src/app/shared/layout/side-nav/side-nav-content.component.ts

On mobile screens, clicking on the context menu link opens the page but does not close the menu.
Closes #
- first commit: added the missing output event for link emit.
- second commit: Refactored the component to generate the template with `@for` to avoid accidentally missing the linkEmit output event whenever someone adds a new field. I can revert this if it feels overkill/restrictive.

fix: Mobile Docs nav menu should close on clicking context-menu link

---

libs/ui/select/brain/src/lib/brn-select.service.ts
libs/ui/select/brain/src/lib/tests/brn-select.component.numbers.spec.ts
libs/ui/select/brain/src/lib/tests/brn-select.component.spec.ts
libs/ui/select/brain/src/lib/tests/select-multi-mode.spec.ts
libs/ui/select/brain/src/lib/tests/select-single-mode.spec.ts

Closes #451
If the trigger element is resized the dropdown will not match the dropdown size. This PR adds a resize observer to update the trigger width on element resize.

fix(select): updating trigger width on element resize

---

libs/cli/src/generators/ui/libs/ui-avatar-helm/files/lib/fallback/hlm-avatar-fallback.directive.ts.template
libs/cli/src/generators/ui/libs/ui-avatar-helm/files/lib/hlm-avatar.component.spec.ts.template
libs/cli/src/generators/ui/libs/ui-avatar-helm/files/lib/hlm-avatar.component.ts.template
libs/ui/avatar/brain/src/lib/brn-avatar.component.ts
libs/ui/avatar/brain/src/lib/fallback/brn-avatar-fallback.directive.ts
libs/ui/avatar/helm/src/lib/fallback/hlm-avatar-fallback.directive.ts
libs/ui/avatar/helm/src/lib/hlm-avatar.component.spec.ts
libs/ui/avatar/helm/src/lib/hlm-avatar.component.ts

Components and directives related to Avatar do not use signals.
Closes #415
Components and directives related to Avatar use signals.
Covered areas:
- HlmAvatarComponent (with updated tests)
- BrnAvatarComponent
- BrnAvatarFallbackDirective
Already using signals:
- HlmAvatarImageDirective
- HlmAvatarFallbackDirective
- BrnAvatarImageDirective
In BrnAvatarComponent, `image` is now a signal, and the type has changed from `BrnAvatarImageDirective | null` to `BrnAvatarImageDirective | undefined`.

refactor(avatar)!: migration to signals

---

libs/cli/src/generators/ui/libs/ui-badge-helm/files/lib/hlm-badge.directive.ts.template
libs/ui/badge/badge.stories.ts
libs/ui/badge/helm/src/lib/hlm-badge.directive.ts

Closes #419
Migrated to input signals and added default values to the Storybook docs.

refactor(badge): migration to signals

---

libs/ui/progress/brain/src/index.ts
libs/ui/progress/brain/src/lib/brn-progress-indicator.component.ts
libs/ui/progress/brain/src/lib/brn-progress.component.spec.ts
libs/ui/progress/brain/src/lib/brn-progress.component.ts
libs/ui/progress/brain/src/lib/brn-progress.token.ts
libs/ui/progress/helm/src/lib/hlm-progress-indicator.directive.ts
libs/ui/progress/helm/src/lib/hlm-progress.directive.ts

Closes #431 
- Migrating progress components/directives to use signals
- Adding unit tests
- Updating to use provider to retrieve value instead of querying the dom in ngDoCheck as that is quite an expensive task in such a frequently run function.

refactor(progress): migration to signals

---

libs/cli/src/generators/ui/libs/ui-scroll-area-helm/files/lib/hlm-scroll-area.component.ts.template
libs/ui/scroll-area/helm/src/lib/hlm-scroll-area.component.ts
libs/ui/scroll-area/scroll-area.stories.ts

Closes #443
Apart from migrating to signals, it looks like the CSS variables have a typo with a missing closing parenthesis. That's fixed here as well.

refactor(scroll-area): migration to signals

---

libs/ui/accordion/helm/src/lib/hlm-accordion-icon.directive.ts
libs/ui/alert/helm/src/lib/hlm-alert-icon.directive.ts
libs/ui/command/helm/src/lib/hlm-command-item-icon.directive.ts
libs/ui/icon/helm/src/index.ts
libs/ui/icon/helm/src/lib/hlm-icon.component.ts
libs/ui/icon/helm/src/lib/hlm-icon.token.ts
libs/ui/icon/icon.stories.ts
libs/ui/menu/helm/src/lib/hlm-menu-item-icon.directive.ts

Closes #417
Components that we previously using the icon as a HostDirective and were setting the inputs programmatically should now use the `provideHlmIconConfig` provider instead.
- `provideHlmIconConfig` for other components to set defaults (pattern from @ashley-hunter #447)

refactor(icon): migrate to signals

---

libs/ui/checkbox/brain/src/lib/brn-checkbox-ng-model.component.spec.ts
libs/ui/checkbox/brain/src/lib/brn-checkbox-ng-model.spec.ts
libs/ui/checkbox/brain/src/lib/brn-checkbox.component.ts
libs/ui/checkbox/helm/src/lib/hlm-checkbox.component.ts

Closes #441
- Replace Output and ViewChild
- Replace internal disabled signal with computed state.

refactor(checkbox): migration to signals

---

apps/app/src/app/pages/(components)/components/(tooltip)/tooltip--simple.example.ts
apps/app/src/app/pages/(components)/components/(tooltip)/tooltip.page.ts
libs/ui/toggle/brain/src/lib/brn-toggle-group.component.spec.ts
libs/ui/toggle/brain/src/lib/brn-toggle-group.component.ts
libs/ui/toggle/brain/src/lib/brn-toggle.directive.ts

There are some imperative calls to update the state.
Closes #
The state is derived in a more reactive way.
The state of the toggle is more coupled to the group (when inside a group).

refactor(toggle): remove imperative calls to updateSelectionState

---

libs/ui/form-field/helm/src/lib/hlm-form-field.component.ts
libs/ui/input/helm/src/lib/hlm-input.directive.ts

refactor(input): migrate to signals

---

apps/app/src/app/pages/(components)/components/(tooltip)/tooltip--simple.example.ts

"Simple"-Example for the tooltips in the docs contains an unused import for `HlmTooltipComponent`.
"Simple"-Example for the tooltips in the docs is more compact and doesn't contain unused imports anymore.

refactor(tooltip): remove unused import

---

libs/ui/pagination/helm/src/lib/hlm-pagination-next.component.ts
libs/ui/pagination/helm/src/lib/hlm-pagination-previous.component.ts

Closes #
Add `ariaLabel` and `text` as inputs for previous/next button for localization.

refactor(pagination): ariaLabel and text as input for localization

---

apps/ui-storybook-e2e/src/integration/select/select.cy.ts
libs/ui/select/brain/src/lib/brn-select-content.component.ts
libs/ui/select/brain/src/lib/brn-select-option.directive.ts
libs/ui/select/brain/src/lib/brn-select-value.component.ts
libs/ui/select/brain/src/lib/brn-select.component.ts
libs/ui/select/brain/src/lib/brn-select.service.ts
libs/ui/select/brain/src/lib/tests/brn-select.component.spec.ts
libs/ui/select/brain/src/test-setup.ts
libs/ui/select/brain/tsconfig.spec.json
libs/ui/select/helm/src/lib/hlm-select-content.directive.ts
libs/ui/select/helm/src/lib/hlm-select-label.directive.ts
libs/ui/select/helm/src/lib/hlm-select-option.component.ts
libs/ui/select/helm/src/lib/hlm-select-trigger.component.ts
libs/ui/select/select.stories.ts
package.json

Disabled Options don't look disabled and are clickable.
Input, Output, ViewChild, ContentChild are in the old @Decorator format.
Closes #452 
Closes #429 
Disabled Options are not clickable anymore and appear as disabled.
Refactoring 
Input, Output, ViewChild, ContentChild are now Signal/Function based.
As all the other refactorings to signal inputs it is not possible anymore to write directly to inputs.
Writing to inputs was never really recommended by the angular team.

refactor: Select signal inputs

---

libs/ui/tabs/brain/src/lib/brn-tabs-paginated-list.directive.ts
libs/ui/tabs/helm/src/lib/hlm-tabs-paginated-list.component.ts

Closes #436
`HlmTabsPaginatedListComponent` must be updated to use `contenChildren`.
Tab changes work fine with keyboard and also with the arrow buttons.

refactor(tabs): use signal contentChildren for paginated tabs

---

libs/ui/pagination/helm/src/lib/hlm-numbered-pagination.component.ts
libs/ui/pagination/helm/src/lib/hlm-pagination-link.directive.ts
libs/ui/pagination/helm/src/lib/hlm-pagination-previous.component.ts

Pagination previous had the wrong `pr-2.5` style applied.
Advanced Pagination hover styles showed the cursor text by default, because `RouterLink` is used as hostDirective for `hlmPaginationLink` and it does not receive a `link`.
Update pagination previous styles to `pl-2.5`.
Add `cursor-pointer` to advanced pagination to `hlmPaginationLink` and previous/next buttons.
Breaking change because styles change and need to copied over

fix(pagination): styles

---

libs/ui/radio-group/brain/package.json
libs/ui/radio-group/brain/src/index.ts
libs/ui/radio-group/brain/src/lib/brn-radio-group.component.ts
libs/ui/radio-group/brain/src/lib/brn-radio-group.token.ts
libs/ui/radio-group/brain/src/lib/brn-radio.component.ts
package.json
pnpm-lock.yaml

Closes #442
I have migrated these directives to use signals, and have been able to significantly reduce the amount of code required. One change I did make - I can revert if we feel its important to retain - but essentially there was the assumption that a radio button may be used without a group. Personally I don't ever think I have seen an instance where a single radio button is used, as typically that would be what a checkbox is for. Accommodating the potential case for a standalone radio button results in potentially multiple sources of truth, for example, a radio button has a …

feat(radio-group): migrate to signals

---

libs/cli/src/generators/ui/generator.ts

Selecting "all" in the CLI causes the task to fail:
Originally posted on discord:
https://discord.com/channels/1145362148621557921/1314345787337080982
This was because importing json resulted in a `default` import being included in the returned data. As there is no `default` component this caused this to fail.

fix: resolving issue preventing cli from generating all components

---

libs/brain/accordion/src/lib/brn-accordion.directive.spec.ts
libs/brain/accordion/src/lib/brn-accordion.directive.ts
libs/ui/accordion/accordion.stories.ts

It's not possible to type "space" inside an input located in the accordion component.
Prevent default is skipped if the target is an input allowing to type "space"
How to replicate:
```html
<hlm-accordion>
<hlm-accordion-item>
<button hlmAccordionTrigger>
Is it accessible?
<hlm-icon hlmAccIcon />
</button>
<hlm-accordion-content>
<input />
Yes. It adheres to the WAI-ARIA design pattern.
</hlm-accordion-content>
</hlm-accordion-item>
</hlm-accordion>
```

fix(accordion): can't write "space" symbol inside accordion

---

libs/brain/accordion/src/lib/brn-accordion.directive.ts

Closes #535 
`BrnAccordionDirective` and `BrnAccordionItemDirective` can now be referenced by template variables with the added `exportAs` declaration.
e.g.
```html
<div brnAccordion hlm #accordion="brnAccordion">
</div>
{{ accordion.openItemIds() }}
```
It's a simple change, I'm not sure if (and how) this should be tested.

feat(accordion): add exportAs for brnAccordionItem and brnAccordion

---

apps/app/src/app/pages/(documentation)/documentation/(ui)/installation.page.ts

Running the Nx plugin or Angular CLI will add the overlay styles to styles entrypoint.  But the section for manual installation doesn't provide any information for Angular CDK overlay styles.
Reminder to import the CDK overlay styles is now added to the UI installation docs below the manually adding variables section.
I've been following the manual installation recently and spent some time debugging the dropdown menu component due to lack of CDK overlay styles import.  I think it could be helpful if we clarify this.

docs: add cdk styles import to manual installation section

---

apps/app/src/app/pages/(components)/components/(dropdown-menu)/dropdown-menu.page.ts
apps/app/src/app/pages/(components)/components/(dropdown-menu)/dropdown-with-context.preview.ts
libs/brain/menu/src/lib/brn-menu-trigger.directive.ts

Closes #
#562 
This feature allows you to pass context to a dropdown menu template.
By using the cdkMenuTriggerData input, data is passed by setting the brnMenuTriggerData directive and then available using the let- keyword in the scope of the template.

feature(dropdown-menu): add brnMenuTriggerData

---

apps/app/src/app/pages/(documentation)/documentation/cli.page.ts
apps/app/src/app/shared/layout/package-installer-tabs.component.ts

add component to display installation commands for package managers.
This PR introduces the PackageInstallerTabsComponent. It displays installation commands for various package managers (npm, pnpm, yarn, bun) in a tabbed interface, allowing users to switch tabs and view the relevant commands dynamically.

docs: add package installer tabs component

---

libs/ui/sheet/helm/src/lib/hlm-sheet-close.directive.ts
libs/ui/sheet/helm/src/lib/hlm-sheet-content.component.ts

the close icon is a little bit too large and does not match the original spartan/shadcn style
Closes #
It is now the same size as it was before the ng-icon migration.
removing the 100% was not enough

fix(sheet): close icon size matches shadcn style

---

apps/app/src/app/pages/(documentation)/documentation/(ui)/figma.page.ts

Bottom navigation of "Health Checks" on the Figma page navigates to the wrong url:
https://spartan.ng/health-checks
Bottom navigation of "Health Checks" on the Figma page navigates to the correct url:
https://spartan.ng/documentation/health-checks

docs: fix bottom nav url to health-checks

---

libs/ui/breadcrumb/helm/src/lib/breadcrumb-separator.component.ts

Aligns separators in the center and reduces the icon size to "sm" to better fit in the general appearance.
Closes #
Current: Out of center and to big. 
New: Vertically centered and smaller.

fix(breadcrumb): vertical alignment of separator

---

libs/cli/src/generators/ui/libs/ui-select-helm/files/lib/hlm-select-option.component.ts.template
libs/ui/select/helm/src/lib/hlm-select-option.component.ts

fix(select): default hlm-select-option icon size

---

apps/ui-storybook-e2e/src/integration/command/command--dynamic.cy.ts
libs/brain/command/src/lib/brn-command-item.directive.ts
libs/ui/command/command.stories.ts

When adding the items of a command via for loop an  NG0950 exception occurs, because the input is not initialized.
the ``BrnCommandEmptyDirective`` calls the visible property via ``contentChildren``. visible() itself is a computed which accesses the value of the ``BrnCommandItemDirective``. 
Usually it is safe to use the input in computeds because inside a component this always is called after the input is initialized. 
The problem here is, that the input is accessed through a computed of another component.
Closes #587 
the directive waits until it is initialized before it accesses …

fix(command): dynamic options are loaded without error

---

libs/brain/command/src/lib/brn-command.directive.ts
libs/ui/command/helm/src/lib/hlm-command.component.ts

valueChanged Event does not exist anymore, but it was implemented in the cmdk version. 
Closes #589 
``valueChanged`` was added and returns the value of the active item.

fix(command): add valueChanged again

---

apps/app/src/app/pages/(components)/components/(data-table)/data-table.preview.ts
apps/app/src/app/pages/(examples)/examples.page.ts
apps/app/src/app/pages/(examples)/examples/tasks/(tasks).page.ts
apps/app/src/app/pages/(examples)/examples/tasks/components/table-actions.component.ts
apps/app/src/app/pages/(examples)/examples/tasks/pipes/priority-icon.pipe.ts
apps/app/src/app/pages/(examples)/examples/tasks/pipes/status-icon.pipe.ts
apps/app/src/app/pages/(examples)/examples/tasks/services/local-storage.service.ts
apps/app/src/app/pages/(examples)/examples/tasks/services/tasks.service.ts

Hey, my goal with this PR is to enhance the current examples with a tasks table.
Adding more examples to the spartan docs demonstrating a complex data table for tasks.
none, just docs
The examples in the app do not showcase complex data tables.
I added an extra example to showcase a complex data table managing tasks (you might have seen that example before ;)) 
I wanted to add that the reason for me pushing to use spartan in my company (and we do now in production across multiple module federated apps), was the amazing feel of working with spartan and the data table was one big selling part.
Therefore, i thought it would be nice to add a more elaborate example to show others what one can achieve with spartan.
Let me know of any improvements i shall make.

docs(data-table): add Tasks example page

---

apps/app/src/app/pages/(components)/components/(command)/command.preview.ts
apps/ui-storybook-e2e/src/integration/command/command--dynamic.cy.ts
libs/brain/command/src/lib/brn-command-item.directive.ts
libs/brain/command/src/lib/brn-command-search-input.directive.ts
libs/brain/command/src/lib/brn-command.directive.ts
libs/ui/command/command.stories.ts
libs/ui/command/helm/src/lib/hlm-command-group.component.ts
libs/ui/command/helm/src/lib/hlm-command-item.component.ts
libs/ui/command/helm/src/lib/hlm-command-list.component.ts
libs/ui/command/helm/src/lib/hlm-command-search-input.component.ts
libs/ui/command/helm/src/lib/hlm-command.component.ts

Typeahead does not feel right and doesn't match shadcn behaviour. 
NG0950 Error can occur still.
Up and down Arrow is not working when searchtext is empty
Setting searchtext via ngModel does not work
Closes #593 
Sorry for adding so much additional fixes to this PR.

fix(command): ngModel is recognized, NG0950 error fixed, focus up and…   … down fixed

---

apps/app/src/app/pages/(documentation)/documentation/(ui)/installation.page.ts
libs/brain/hlm-tailwind-preset.css
libs/brain/ng-package.json
libs/brain/package.json
libs/cli/src/generators/theme/generator.spec.ts
libs/cli/src/generators/theme/libs/add-theme-to-application-styles.ts
package.json
pnpm-lock.yaml

N/A
Adding support for Tailwind 4. This adds tailwind version detection to the theme generator and adds the preset import automatically if Tailwind 4 is detected.

feat: adding support for tailwind 4

---

libs/brain/alert-dialog/src/lib/brn-alert-dialog-trigger.directive.ts
libs/brain/alert-dialog/src/lib/brn-alert-dialog.component.ts
libs/brain/dialog/src/index.ts
libs/brain/dialog/src/lib/brn-dialog-close.directive.ts
libs/brain/dialog/src/lib/brn-dialog-content.directive.ts
libs/brain/dialog/src/lib/brn-dialog-overlay.component.ts
libs/brain/dialog/src/lib/brn-dialog-token.ts
libs/brain/dialog/src/lib/brn-dialog-trigger.directive.ts
libs/brain/dialog/src/lib/brn-dialog.component.ts
libs/brain/popover/src/lib/brn-popover-trigger.directive.ts
libs/brain/popover/src/lib/brn-popover.component.ts
libs/brain/sheet/src/lib/brn-sheet-trigger.directive.ts
libs/brain/sheet/src/lib/brn-sheet.component.ts
libs/ui/alert-dialog/helm/src/lib/hlm-alert-dialog-overlay.directive.ts
libs/ui/alert-dialog/helm/src/lib/hlm-alert-dialog.component.ts
libs/ui/dialog/helm/src/lib/hlm-dialog-overlay.directive.ts
libs/ui/dialog/helm/src/lib/hlm-dialog.component.ts
libs/ui/sheet/helm/src/lib/hlm-sheet-overlay.directive.ts
libs/ui/sheet/helm/src/lib/hlm-sheet.component.ts

Closes #427 
Closes #423 
Closes #425
As all Signal input changes, this PR has the potential of breaking the code, if a user was writing directly to an input.
This PR builds ontop of the work of @MerlinMoos 
https://github.com/spartan-ng/spartan/pull/505

refactor(dialog,sheet,popover): migrate to signals

---

apps/app/src/app/pages/(components)/components/(card)/card.preview.ts
apps/app/src/app/pages/(components)/components/(combobox)/combobox.preview.ts
apps/app/src/app/pages/(components)/components/(command)/command--dialog.example.ts
apps/app/src/app/pages/(components)/components/(popover)/popover.preview.ts
apps/app/src/app/shared/header/header-mobile-nav.component.ts
libs/brain/alert-dialog/src/lib/brn-alert-dialog.component.ts
libs/brain/dialog/src/lib/brn-dialog-options.ts
libs/brain/dialog/src/lib/brn-dialog-token.ts
libs/brain/dialog/src/lib/brn-dialog.component.ts
libs/brain/popover/src/lib/brn-popover.component.ts
libs/cli/src/generators/ui/libs/ui-alert-dialog-helm/files/lib/hlm-alert-dialog.component.ts.template
libs/cli/src/generators/ui/libs/ui-date-picker-helm/files/lib/hlm-date-picker.component.ts.template
libs/cli/src/generators/ui/libs/ui-dialog-helm/files/lib/hlm-dialog.component.ts.template
libs/cli/src/generators/ui/libs/ui-dialog-helm/files/lib/hlm-dialog.service.ts.template
libs/cli/src/generators/ui/libs/ui-sheet-helm/files/lib/hlm-sheet.component.ts.template
libs/ui/alert-dialog/helm/src/lib/hlm-alert-dialog.component.ts
libs/ui/combobox/combobox.stories.ts
libs/ui/command/command.stories.ts
libs/ui/date-picker/helm/src/lib/hlm-date-picker.component.ts
libs/ui/dialog/helm/src/lib/hlm-dialog.component.ts
libs/ui/dialog/helm/src/lib/hlm-dialog.service.ts
libs/ui/popover/popover.stories.ts
libs/ui/sheet/helm/src/lib/hlm-sheet.component.ts

* change closeDelay to 100 default
* use closeDelay input value
* use defaultOptions values for input signal defaults
Closes #608
`provideBrnDialogDefaultOptions` needs to be added to `HlmAlertDialogComponent`
```ts
import {
BRN_ALERT_DIALOG_DEFAULT_OPTIONS,
} from '@spartan-ng/brain/alert-dialog';
import { provideBrnDialogDefaultOptions } from '@spartan-ng/brain/dialog';
providers: [
...,
provideBrnDialogDefaultOptions({
...BRN_ALERT_DIALOG_DEFAULT_OPTIONS,
}),
],
```

feat(dialog): add more dialog options to BrnDialogDefaultOptions

---

apps/app/src/app/pages/(components)/components/(icon)/icon.preview.ts

Missing import `import { NgIcon, provideIcons } from '@ng-icons/core';` in the docs
Closes #619

docs(icon): add missing NgIcon imports (#619)

---

libs/cli/src/generators/ui/libs/ui-alert-dialog-helm/files/lib/hlm-alert-dialog-overlay.directive.ts.template
libs/cli/src/generators/ui/libs/ui-dialog-helm/files/lib/hlm-dialog-overlay.directive.ts.template
libs/cli/src/generators/ui/libs/ui-sheet-helm/files/lib/hlm-sheet-overlay.directive.ts.template
libs/ui/alert-dialog/helm/src/lib/hlm-alert-dialog-overlay.directive.ts
libs/ui/dialog/helm/src/lib/hlm-dialog-overlay.directive.ts
libs/ui/sheet/helm/src/lib/hlm-sheet-overlay.directive.ts

Now the overlay of dialog, alert dialog and sheet have different color
Closes #621 
The overlay of dialog, alert dialog and sheet will look like shadcn
dialog:
alert dialog:
sheet:

fix(dialog): overlay styles

---

libs/brain/select/src/lib/brn-select-value.component.ts
libs/brain/select/src/lib/brn-select.component.ts

Ensure correct behavior on select value level when custom compare with function is provided to the select component
When a custom `compareWith` function is provided to the `SelectComponent` it's not used in the `BrnSelectValueComponent`. This leads to inconsistent behavior as the selected value isn't shown in the `BrnSelectValueComponent` because the comparison returns false.
The comparison in the `BrnSelectValueComponent` is fixed to reference equality and doesn't account for the custom compare function.
Always use the custom compare function which falls back to comparing reference …

fix(select): use compare with function

---

libs/ui/switch/helm/src/lib/hlm-switch.component.ts

Currently, the HlmSwitchComponent does not implement the ControlValueAccessor interface, so the disabled state cannot be managed via Angular forms. This limits the integration and consistency of state management within form controls.
The HlmSwitchComponent now implements the ControlValueAccessor interface and includes the setDisabledState method. This enhancement enables the component to properly handle and reflect the disabled state when used within Angular forms, improving its interoperability with form APIs.

Implement setDisabledState on ControlValueAccessor in HlmSwitchComponent

---

apps/app/src/app/pages/(documentation)/documentation/(ui)/installation.page.ts

Hey, my goal with this PR is to improve the project's installation experience.
Closes #
I've created a new Angular project from scratch and without googling it was super hard to run the project with proper tailwind configuration, but with this documentation improvement a lot of hours could be saved.

docs(repo): add tailwind configuration troubleshooting

---

libs/cli/src/generators/migrate-radio/generator.spec.ts
libs/cli/src/generators/migrate-radio/generator.ts

health-check migrations
the migration for hlm-radio only replaces ``<brn-radio hlm`` occurrences.
If some codebases have different formatting and the ``hlm`` attribute is not directly after the ``brn-radio`` tag, the migration fails to find these.
also replaces 
```
<brn-radio 
hlm>
<brn-radio class="foo" hlm>
```

fix: radio migration also finds tags with linebreaks

---

libs/cli/src/generators/ui/libs/ui-breadcrumb-helm/files/lib/breadcrumb-separator.component.ts.template
libs/ui/breadcrumb/helm/src/lib/breadcrumb-separator.component.ts

Breadcrumb separator style have wrong style with tailwind v4 and ng-icon
Default icon size is 16px and align to top
Closes #
Default icon is 14px and align center
Breadcrumb

fix(breadcrumb): breadcrumb separator icon style

---

libs/brain/tooltip/src/lib/brn-tooltip-trigger.directive.ts

---
---
---
When using `BrnTooltipTriggerDirective` as a `hostDirective`, it's not possible to programmatically set `tooltipContentClasses` since it is defined using `input()`, which is readonly in Angular's signal system.
---
This PR updates the `tooltipContentClasses` field in `BrnTooltipTriggerDirective` from an `input()` to a `model()`.
This allows:
- Two-way binding via the `Input`
- Programmatic updates using `.set()` — which is currently not possible with `input()`
---
```ts
@Directive({
selector: '[myCustomTooltipTrigger]',
standalone: true,
hostDirectives: [{
directive: BrnTooltipTriggerDirective,
inputs: ['brnTooltipTrigger'],
}]
})
export class MyCustomTooltipTriggerDirective {
private readonly variant = input<'default' | …
```

fix(tooltip): allow programmatic control of tooltipContentClasses

---

libs/brain/select/src/lib/brn-select.component.ts
libs/brain/select/src/lib/tests/select-multi-mode.spec.ts
libs/brain/select/src/lib/tests/select-reactive-form.ts

Closes #666
When in multi select mode it makes more sense for a select to return an empty array rather than null. This simplifies things as it avoids having to deal multiple data types.
This is potentially a breaking change, but probably a better default that could help prevent bugs in apps.

fix(select): multi select defaults to empty array

---

libs/brain/date-time-luxon/src/lib/date-adapter.spec.ts
libs/brain/date-time-luxon/src/lib/date-adapter.ts
libs/brain/date-time/src/lib/date-adapter.ts
libs/brain/date-time/src/lib/native-date-adapter.spec.ts

Added tests
`getDay()` in `BrnLuxonDateAdapter` returns a value between 1-7 whereas a value between 0-6 is expected.
Closes #675 
Adapt the `BrnLuxonDateAdapter` to return a value in the range 0-6.

fix: ensure BrnLuxonDateAdapter#getDay() returns a value between 0 and 6

---

apps/app/src/app/pages/(components)/components/(carousel)/carousel--orientation.example.ts
apps/app/src/app/pages/(components)/components/(carousel)/carousel--plugins.example.ts
apps/app/src/app/pages/(components)/components/(carousel)/carousel--sizes.example.ts
apps/app/src/app/pages/(components)/components/(carousel)/carousel--slide-count.example.ts
apps/app/src/app/pages/(components)/components/(carousel)/carousel--spacing.example.ts
apps/app/src/app/pages/(components)/components/(carousel)/carousel.page.ts
apps/app/src/app/pages/(components)/components/(carousel)/carousel.preview.ts
libs/ui/carousel/helm/src/index.ts
libs/ui/carousel/helm/src/lib/hlm-carousel-slide-display.component.ts
libs/ui/carousel/helm/src/lib/hlm-carousel.component.ts

`HlmCarouselComponent` uses `@ViewChild(EmblaCarouselDirective)` and does not track the current slide and total slide count.
`HlmCarouselComponent` uses `viewChild.required(EmblaCarouselDirective)` and tracks `currentSlide` and `slideCount`. Adds new component `hlm-carousel-slide-display` to display the slide counts
Code snippets are also updated for carousel examples.

feat(carousel): use viewChild() and add slide count component

---

libs/brain/tabs/src/lib/brn-tabs-content.directive.ts
libs/brain/tabs/src/lib/brn-tabs-trigger.directive.ts
libs/brain/tabs/src/lib/brn-tabs.directive.spec.ts
libs/brain/tabs/src/lib/brn-tabs.directive.ts

Closes #710 
The brnTabsTrigger and brnTabsContent unregisters onDestroy. Active tab is set as undefined when trigger is removed
I'm not sure if an event with active tab to undefined should be emitted after destroying a card. I can image situation where we want to destroy tab but user should stay at actived content. On the other hand it seems logical. I ran unit tests the tests but not all pass (eg. test for tools) on my local env even without my changes. I compared output and seems the same. Also wondered if there should be a common function for those methods but decided to go that …

feat(tabs): add unregister functionality to BrnTabsDirective (#710)

---

apps/app/src/app/pages/(components)/components/(progress)/progress.preview.ts

Added missing HlmProgressDirective import.
The **Progress Bar** documentation preview is missing the import of HlmProgressDirective. As a result, when copying the example code directly, the styles do not apply correctly.
Closes #
The example now includes the import of HlmProgressDirective, ensuring the styles are applied correctly and the preview renders as intended.

fix(docs): added missing HlmProgressDirective to documentation

---

commitlint.config.cjs
libs/cli/src/generators/base/generator.ts

closes #723
We get the wrong separator in the tsconfig if running on windows
Closes #723

fix(cli): make sure to use the right separator regardless of OS

---

apps/app/src/app/pages/(components)/components/(tabs)/tabs.page.ts
apps/app/src/app/pages/(components)/components/(tabs)/tabs.preview.ts
libs/helm/tabs/src/lib/hlm-tabs-list.component.ts
libs/helm/tabs/src/lib/hlm-tabs.component.ts

Styles for vertical orientation was not correctly applied. It should be `h-fit` but it is overridden by `h-9` from the `userClass`.
Update styles in `listVariants` and remove unnecessary `userClass` in `hlm-tabs` and `hlm-tabs-list`.
Format usage code and update fix formatting issue with `hlmAlertDesc`.

fix(tabs): vertical styles and format tabs snippet

---

apps/app/src/app/pages/(components)/components/(calendar)/calendar.preview.ts
libs/helm/calendar/src/lib/hlm-calendar.component.ts

Hover active date and the text is not readable in light mode
Hover active date and the text is readable in light mode

fix(calendar): hover active styles in light mode

---

apps/ui-storybook-e2e/src/integration/dialog/dialog.cy.ts
libs/brain/dialog/src/lib/brn-dialog-trigger.directive.ts

When a dialog (or any primitive using brnDialogTrigger, such as popover, alert-dialog, or combobox) is toggled open or closed, the trigger element's aria-expanded attribute incorrectly remains false, causing accessibility inconsistencies.
Closes #739 
The aria-expanded attribute on the trigger element now reflects the actual open/closed state of the dialog. The BrnDialogTriggerDirective's state property has been converted to a computed signal that dynamically tracks dialog state from the correct source (input, injected component, or ref). This also improves support for nested dialogs. …

Dialog trigger should update aria-expanded to reflect open state

---

apps/app/src/app/pages/(components)/components.page.ts
apps/app/src/app/pages/(components)/components/(alert)/alert--destructive.example.ts
apps/app/src/app/pages/(components)/components/(alert)/alert.generated.ts
apps/app/src/app/pages/(components)/components/(alert)/alert.preview.ts
apps/app/src/app/pages/(components)/components/(tabs)/tabs.page.ts
apps/app/src/app/pages/(documentation)/documentation/(ui)/theming.page.ts
apps/app/src/app/pages/(stack)/stack/installation.page.ts
apps/ui-storybook/stories/alert.stories.ts
libs/cli/src/generators/ui/libs/ui-alert-helm/files/lib/hlm-alert.directive.ts.template
libs/helm/alert/src/lib/hlm-alert.directive.ts

Alert usage needs to be updated for the new-york styles
Use `theme(spacing.1)` instead of `var(--spacing)` in `hlmAlert` styles. `var(--spacing)` is only supported in Tailwind v4.

docs: fix alert usage and polish alert preview/imports

---

apps/ui-storybook-e2e/src/integration/radio-group/radio-group.cy.ts
apps/ui-storybook/stories/radio-group.stories.ts
libs/brain/radio-group/src/lib/brn-radio.component.ts
libs/helm/label/src/lib/hlm-label.directive.ts
libs/helm/radio-group/src/lib/hlm-radio.component.ts

When using the label side by side with the radio box and use "label for" the same way like with the checkbox, clicking on the label does not check the radio item.
While testing this PR i saw that the disabled state is not displayed.  
Closes #779 
It also checks the radio when using the label for method.
Cursor not allowed and opacity are set to the indicator directly, (same way as checkbox)
``has-[[disabled]]:cursor-not-allowed has-[[disabled]]:opacity-50`` was added to the label, show the disabled state of the label, if there are disabled elements inside the content of a label. …

fix(radio-group): id for container is set, disabled state is displayed

---

apps/app/src/app/pages/(documentation)/documentation/components-json.page.ts
libs/cli/src/generators/base/generator.spec.ts
libs/cli/src/generators/base/lib/initialize-angular-library.ts
libs/cli/src/generators/base/schema.d.ts
libs/cli/src/generators/ui/generator.ts
libs/cli/src/utils/config.ts

Libs are generated always as buildable
Closes #805 
Add config flag to make in non buildable

feat(cli): add config flag for non-buildable libs #805

---

libs/cli/src/generators/ui/libs/ui-tooltip-helm/files/lib/hlm-tooltip-trigger.ts.template
libs/helm/tooltip/src/lib/hlm-tooltip-trigger.ts

Currently the template file `hlm-tooltip-trigger.ts.template` and the `hlm-tooltip-trigger.ts` contain a syntax error in the definition of the `DEFAULT_TOOLTIP_CONTENT_CLASSES` constant. I assume the intention was to concatenate all strings. The semicolon at the end of line 5 should rather be a +.
The syntax error is resolved and correct string concatenation is used.

fix(tooltip): correct syntax in default content classes definition

---

apps/app/src/app/pages/(components)/components/(alert-dialog)/alert-dialog.page.ts
apps/app/src/app/pages/(components)/components/(alert-dialog)/alert-dialog.preview.ts
apps/ui-storybook/stories/alert-dialog.stories.ts
libs/brain/alert-dialog/src/lib/brn-alert-dialog-trigger.ts
libs/helm/alert-dialog/src/lib/hlm-alert-dialog-action-button.ts
libs/helm/alert-dialog/src/lib/hlm-alert-dialog-cancel-button.ts
libs/tools/src/executors/docs/generate-ui-docs/__snapshots__/executor.spec.ts.snap

- install script `alertdialog` only opens the selection and doesn't generate the alert-dialog component directly
- update install script to use `alert-dialog` instead of `alertdialog`
- update docs preview code and snippet
- expose button inputs for cancel and action button - allows for quick customization like destructive for the action
- remove additional mt from cancel button
- add default `type` to trigger button

feat: alert dialog polishing

---

libs/brain/button/README.md
libs/brain/button/ng-package.json
libs/brain/button/src/index.ts
libs/brain/button/src/lib/brn-button.spec.ts
libs/brain/button/src/lib/brn-button.ts
libs/helm/button/src/lib/hlm-button.ts
tsconfig.base.json

Currently it's not possible to to disable a hlmBtn on a <a> element
Closes #797

feat(button): add anchor button #797

---

apps/app/src/app/pages/(documentation)/documentation/(ui)/installation.page.ts
apps/app/src/styles.css
libs/cli/src/generators/theme/__snapshots__/generator.spec.ts.snap
libs/cli/src/generators/theme/libs/add-theme-to-application-styles.ts

1. `color-scheme: light;` and `color-scheme: dark;` is part of the installation style snippet, but is not included when running `npx nx g @spartan-ng/cli:ui-theme`.
2. `color-scheme: light;` and `color-scheme: dark;` is not used in the spartan docs app, thus scrollbars don't change colors in dark mode (https://github.com/spartan-ng/spartan/pull/853#issuecomment-3237164134)
Include `color-scheme: light;` and `color-scheme: dark;` in `npx nx g @spartan-ng/cli:ui-theme` and the spartan docs. Change the order of css in the installation guide

fix: include color scheme in cli ui-theme

---

libs/brain/select/src/lib/brn-select-content.ts
libs/brain/select/src/lib/brn-select-option.ts
libs/brain/select/src/lib/brn-select.ts
libs/helm/select/src/lib/hlm-select-option.ts

- fix focus styling
Closes #773 
Not sure if we consider the outline change a breaking change? Might mess with peoples styles?

fix(select): voiceover navigatability and typehead restored

---

apps/app/src/app/pages/(components)/components/(data-table)/data-table.page.ts
apps/app/src/app/pages/(components)/components/(dialog)/dialog-declarative.preview.ts
apps/app/src/app/pages/(components)/components/(dialog)/dialog.page.ts
apps/app/src/app/pages/(components)/components/(dialog)/dialog.preview.ts
libs/brain/dialog/src/lib/brn-dialog.ts
libs/brain/hlm-tailwind-preset.css
libs/brain/hlm-tailwind-preset.js
libs/brain/popover/src/lib/brn-popover-trigger.ts
libs/brain/popover/src/lib/brn-popover.ts
libs/brain/sheet/src/lib/brn-sheet.ts
libs/helm/alert-dialog/src/lib/hlm-alert-dialog-content.ts
libs/helm/dialog/src/lib/hlm-dialog-close.ts
libs/helm/dialog/src/lib/hlm-dialog-content.ts
libs/helm/dialog/src/lib/hlm-dialog-footer.ts
libs/helm/dialog/src/lib/hlm-dialog-header.ts
libs/helm/dialog/src/lib/hlm-dialog-overlay.ts
libs/helm/dialog/src/lib/hlm-dialog-title.ts

Dialog close button height is not 16px instead 24px and focus ring is in a weird shape
- update dialog styles to the latest shadcn/ui styles and sort classes
- fix dialog close button height w/ flex classes
- add `--radius-xs: 0.125rem` to tailwind preset - is used for the dialog close button border radius in shadcn/ui (other components use it too)
- update docs to include example headings, update form field and preview
- update bottom nav in docs

feat: dialog polishing
