README.md
NA
`yarn nx serve analog-trpc` is not working 
Closes #21 
Update the command in readme file
=> fix(docs): updated README file

apps/app/src/app/pages/(stack)/stack/installation.page.ts
Quick clarification to help newer folks out.
Closes #
=> docs: update drizzle installation instructions for clarity

apps/app/src/app/pages/(stack)/stack/installation.page.ts, apps/app/src/db.ts
=> fix: remove use of deprecated type from Drizzle

apps/app/src/main.server.ts
this will invoke Angular's Domino setup.
Which allows access to browser elements like HTMLElement in a SSR environment.
Closes #19
running yarn dev causes HTMLElement not defined error
Closes #19
Dev server works as expected
Thanks to @brandonroberts for the fix!
=> fix: add @angular/platform-server/init to main.server.ts

apps/app/src/app/pages/(stack)/stack/installation.page.ts
When copying and pasting the Code to create the note table in supabase the following error is shown:
> relation "note_id_seq" does not exist
>
> LINE 3:     id bigint not null default nextval('note_id_seq'::regclass),
and the "note" table will not be created
The "note" table is created without an error
=> docs: create sequence for table note

apps/app/src/app/pages/(stack)/stack/installation.page.ts
=> docs: fix title of spartan/stack installation page

apps/app/src/app/pages/(stack)/stack/installation.page.ts
=> docs: built index.mjs is inside server folder

apps/app/src/app/pages/(documentation)/documentation/(ui)/(typography)/typography.preview.ts
Typography class imports (e.g. `hlmH1`) are not used in the code example
=> docs: fix typography import in code examples

apps/app/src/app/pages/(components)/components/(button)/button--loading.example.ts
=> docs: fix example code loading button

apps/app/src/app/pages/(components)/components/(checkbox)/checkbox.page.ts
Command is still using the nx package `npx nx g @spartan-ng/nx:ui checkbox`
Updating to use the cli package `npx nx g @spartan-ng/cli:ui checkbox`
=> fix checkbox command, use cli package

apps/app/src/app/pages/(components)/components/(checkbox)/checkbox.page.ts, libs/cli/src/generators/ui/generator.ts, libs/ui/checkbox/brain/src/lib/brn-checkbox.component.ts
added generator dependency to icon.
removed tailwind from brn
The default Checkbox in brn is hidden by tailwind "sr-only", this does not work if someone does not use tailwind for hlm. 
When adding the checkbox via generators, the icon is not added automatically, it must be added manually to make it work correctly.
The angular/CLI part in the documentation is missing.
Closes #
The default Checkbox in brn is hidden by ngStyle. 
Added dependency to Icon for checkbox generator.
The angular/CLI part shows how to import the checkbox.
=> fix(checkbox): updated docs, fix generator dependency, removed tailwind from brn

libs/ui/scroll-area/helm/src/lib/hlm-scroll-area.component.ts
=> fix(scroll-area): autoWidthDisabled input name typo

apps/app/src/app/pages/(components)/components/(card)/card.preview.ts
By now, the "Framework" control at card preview is using select to show the list.
Using popover at this control.
=> fix(card): update card preview select

libs/ui/icon/helm/src/lib/hlm-icon.component.ts
Closes #
The build is completed without any issues.
=> fix: remove @ts-expect-error from hlm-icon

README.md
=> docs: Add note to add .env to .gitignore

libs/ui/badge/badge.stories.ts, libs/ui/badge/helm/src/lib/hlm-badge.directive.ts
- we are currentely unable to change size
- badge has now size input with 2 options (`default`, `lg`)
=> feat(badge): size input added

libs/cli/src/generators/base/versions.ts, package.json, yarn.lock
Update dependency "tailwind-merge" to v2
Migration Guide can be found here: https://github.com/dcastil/tailwind-merge/blob/v2.0.0/docs/changelog/v1-to-v2-migration.md
=> chore: update tailwind-merge to v2

libs/ui/accordion/helm/src/lib/hlm-accordion-item.directive.ts
Fixes a breaking change mentioned by @elite-benni that was introduced from accordion api refactor (#126) 
Fixes breaking change
=> fix(accordion): re-adds brn+hlm selector to accordion-item

apps/ui-storybook-e2e/src/integration/accordion/accordion.cy.ts
Fixes accordion cypress tests with updated accordion hlm api used in accordion story
Closes #
=> fix(accordion): updates tests with new hlm api

.github/ISSUE_TEMPLATE/01-bug-report.yml, commitlint.config.js, libs/ui/spinner/spinner.stories.ts
- spinner is missing in storybook but it is implemented
- spinner is present in storybook
=> chore(spinner): missing spinner stories added

libs/cli/src/generators/ui/libs/ui-card-helm/files/lib/hlm-card-content.directive.ts.template, libs/cli/src/generators/ui/libs/ui-card-helm/files/lib/hlm-card-description.directive.ts.template, libs/cli/src/generators/ui/libs/ui-card-helm/files/lib/hlm-card-footer.directive.ts.template, libs/cli/src/generators/ui/libs/ui-card-helm/files/lib/hlm-card-header.directive.ts.template, libs/cli/src/generators/ui/libs/ui-card-helm/files/lib/hlm-card-title.directive.ts.template, libs/cli/src/generators/ui/libs/ui-card-helm/files/lib/hlm-card.directive.ts.template, libs/ui/card/helm/src/lib/hlm-card-content.directive.ts, libs/ui/card/helm/src/lib/hlm-card-description.directive.ts, libs/ui/card/helm/src/lib/hlm-card-footer.directive.ts, libs/ui/card/helm/src/lib/hlm-card-header.directive.ts, libs/ui/card/helm/src/lib/hlm-card-title.directive.ts, libs/ui/card/helm/src/lib/hlm-card.directive.ts
=> refactor(card): use input signal

.github/workflows/chromatic.yml
Chromatic failing on pr's blaming issue on single commit checkout
Closes #
=> ci: chromatic fail on checkout issue

apps/app/src/app/pages/(documentation)/documentation/(ui)/installation.page.ts
When installing a fresh spartan repo and trying to run it, it fails because of  ```Could not resolve "@angular/cdk/overlay-prebuilt.css"```, which is added by the generator automatically. 
Closes #
The installation of angular/cdk is added as a prerequisite in the installation page.
=> docs: add angular cdk to prerequisites

apps/app/src/app/pages/(components)/components/(spinner)/spinner.page.ts, apps/app/src/app/pages/(components)/components/(spinner)/spinner.preview.ts, apps/app/src/app/pages/(components)/components/(switch)/switch.page.ts, apps/app/src/app/shared/layout/side-nav/side-nav-content.component.ts, libs/ui/spinner/helm/src/lib/hlm-spinner.component.ts
There was was no page for spinner. 
Closes #
Spinner page added to documentation to make it more public.
=> docs(spinner): add spinner page

libs/ui/pagination/helm/src/lib/hlm-pagination.directive.ts
`role` and `aria-label` for `hlmPagination` are not applied.
Apply `role` and `aria-label` correctly as string.
=> fix(pagination): apply attr as string

.github/ISSUE_TEMPLATE/02-feature-request.yml, .github/PULL_REQUEST_TEMPLATE.md, README.md, apps/app/src/app/pages/(components)/components/(pagination)/pagination.page.ts, apps/app/src/app/pages/(components)/components/(spinner)/spinner.page.ts, libs/ui/README.md
Update meta data for spinner component page and remove unused code from pagination page. Add spinner to templates and update component roadmap count.
=> Update docs for spinner and pagination

CONTRIBUTING.md, apps/app/src/app/pages/(components)/components/(card)/card.page.ts, apps/app/src/app/pages/(components)/components/(carousel)/carousel.page.ts, apps/app/src/app/pages/(components)/components/(carousel)/carousel.preview.ts, apps/app/src/app/shared/layout/side-nav/side-nav-content.component.ts, apps/ui-storybook-e2e/src/integration/carousel/carousel.cy.ts, commitlint.config.js, libs/ui/carousel/carousel.stories.ts, libs/ui/carousel/helm/.eslintrc.json, libs/ui/carousel/helm/README.md, libs/ui/carousel/helm/jest.config.ts, libs/ui/carousel/helm/ng-package.json, libs/ui/carousel/helm/package.json, libs/ui/carousel/helm/project.json, libs/ui/carousel/helm/src/index.ts, libs/ui/carousel/helm/src/lib/hlm-carousel-content.component.ts, libs/ui/carousel/helm/src/lib/hlm-carousel-item.component.ts, libs/ui/carousel/helm/src/lib/hlm-carousel-next.component.ts, libs/ui/carousel/helm/src/lib/hlm-carousel-previous.component.ts, libs/ui/carousel/helm/src/lib/hlm-carousel.component.ts, libs/ui/carousel/helm/src/test-setup.ts, libs/ui/carousel/helm/tsconfig.json, libs/ui/carousel/helm/tsconfig.lib.json, libs/ui/carousel/helm/tsconfig.lib.prod.json, libs/ui/carousel/helm/tsconfig.spec.json, package.json, pnpm-lock.yaml, tsconfig.base.json
=> feat(carousel): add carousel component

apps/app/src/app/pages/(components)/components/(avatar)/avatar.page.ts
tabsCliComponent was imported twice. 
Closes #
=> refactor: remove duplicate import

.github/workflows/chromatic.yml, .github/workflows/ci.yml, .github/workflows/release.yml
* fixing "Node.js 16 actions are deprecated." warnings
Actions showing a warning
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
Updates checkout and setup-node which uses node 20.
=> ci: update checkout and setup-node version

libs/ui/card/helm/src/lib/hlm-card-header.directive.ts
=> fix(card): remove unused direction signal

.github/ISSUE_TEMPLATE/01-bug-report.yml, .github/ISSUE_TEMPLATE/02-feature-request.yml, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Closes #217 
I should be able to select Icon :)
=> feat(docs): adding icon to issue and PR templates 

.editorconfig
.editorconfig has set **space** and .prettierrc **tabs**
sync .editorconfig with the prettier config so it use **tabs** for indent
=> chore: sync .editorconfig with.prettierrc to use tabs for indentation

apps/app/src/app/pages/(components)/components/(sonner)/sonner.preview.ts
Documentation page of Sonner shows incorrect import (Copy paste mistake 😅)
Closes #
Correct import of `HlmToasterComponent` as well as an indentation fix in the code preview
=> fix(sonner): docs preview code and usage

README.md, apps/app/src/app/pages/(components)/components/(data-table)/data-table.preview.ts, apps/app/src/app/pages/(home)/components/three-hundred.component.ts
=> docs: add ragul to member of 300

libs/ui/select/helm/src/lib/hlm-select-content.directive.ts, libs/ui/select/helm/src/lib/hlm-select-group.directive.ts, libs/ui/select/helm/src/lib/hlm-select-label.directive.ts, libs/ui/select/helm/src/lib/hlm-select-option.component.ts, libs/ui/select/helm/src/lib/hlm-select-trigger.component.ts, libs/ui/select/helm/src/lib/hlm-select-value.directive.ts, libs/ui/select/helm/src/lib/hlm-select.directive.ts, libs/ui/separator/helm/src/lib/hlm-separator.directive.ts, libs/ui/spinner/helm/src/lib/hlm-spinner.component.ts, libs/ui/toggle/helm/src/lib/hlm-toggle.directive.ts
=> feat(select,spinner,separator,toggle): more input signals

apps/app/src/app/pages/(components)/components/(checkbox)/checkbox.page.ts
Move the bottom nav of the checkbox doc page to the end of the page
Closes #
=> docs(checkbox): move bottom nav to the end of the page

apps/app/src/app/pages/(home)/components/th-item.component.ts, apps/app/src/app/shared/spartan-logo.component.ts
add hover:cursor-pointer to the 300 image and href to github contributor's profile
closes: issue #226
=> docs: the 300 image clickable

README.md, commitlint.config.cjs
@snydertechnologies will be adopting and contributing financially and with code to the repo
We've been following since the beginning ... really love the work being done here.
Thx
=> feat(repo): add snydertechnologies to spartan 300

apps/app/src/app/pages/(components)/components/(hover-card)/hover-card.page.ts, apps/app/src/app/pages/(components)/components/(icon)/icon.page.ts, apps/app/src/app/pages/(components)/components/(icon)/icon.preview.ts, apps/app/src/app/pages/(components)/components/(input)/input.page.ts, apps/app/src/app/shared/layout/side-nav/side-nav-content.component.ts
=> feat(icon): add icon page

apps/app/src/app/pages/(components)/components/(context-menu)/context-menu.preview.ts
=> docs(context-menu): fixed missing closing tag in example

apps/app/src/app/pages/(components)/components/(button)/button--with-icon.example.ts
=> docs(button): removed un-used import in example

apps/app/src/app/pages/(components)/components/(dropdown-menu)/dropdown-menu.preview.ts
=> docs: use hlm-menu in usage example

apps/app/index.html
https://github.com/goetzrobin/spartan/assets/8985933/940a43fc-53ec-496c-8125-a59930a39aeb
https://github.com/goetzrobin/spartan/assets/8985933/a20b1335-d677-4e56-8f8c-47c0521b9313
=> docs: add scroll behavior smooth for toc

apps/app/src/app/pages/(components)/components/(alert-dialog)/alert-dialog.preview.ts
Opening tag of him-alert-dialog has a mismatched closing element tag.
Closes #
=> docs: fix alert dialog usage example code

README.md, apps/app/src/app/pages/(home)/components/three-hundred.component.ts
=> docs: update contributors list

apps/app/src/app/pages/(components)/components/(accordion)/accordion.preview.ts
=> style(accordion): fix padding in code sample

apps/app/src/app/pages/(components)/components/(dialog)/dialog.preview.ts
- [ X] The commit message follows our
- [ X] Docs have been added / updated (for bug fixes / features)
- [ X] Documentation content changes
- [ X] dialog
Closes #
- [ X] No
=> docs: fix dialog usage example code

apps/app/src/app/pages/(documentation)/documentation/(ui)/theming.page.ts
Angular uses class instead of className, and the sample code in theming page used className instead
Closes #
The sample code in theming page uses class instead of className
=> docs: change className to class in theming page

libs/cli/src/generators/ui/supported-ui-libraries.json, package.json, pnpm-lock.yaml
Closes #
ngx-sonner has been updated to use angular v18 🎉
=> chore: update ngx-sonner to v2.0.0

apps/app/src/styles.css, libs/cli/src/generators/theme/libs/add-theme-to-application-styles.ts
=> fix(tooltip): using aria describedby is causing a blank line at the end of the page

apps/app/src/app/pages/(components)/components/(data-table)/data-table.preview.ts
=> feat: update size options height for data table

libs/ui/tabs/brain/src/lib/brn-tabs-paginated-list.directive.ts
Currently the Tabs page is failing to load due to a compilation error.
The Tabs page is loading.
Fixes issue with compiling the brn-paginated-tabs-list component.
Also fixes some lint issues/warnings.
=> fix(tabs): use inject instead of constructor

apps/app/src/app/pages/(documentation)/documentation/(ui)/installation.page.ts, libs/cli/src/generators/theme/libs/supported-theme-generator-map.ts, libs/ui/storybook/.storybook/tailwind.css
n/a
Scrollbars aren't getting colored:
Closes #
not quite sure whether this change belongs to a library or a userland code, but it was useful for me
https://github.com/user-attachments/assets/68196824-abdf-434e-bc12-1b752f01a438
=> feat: color scheme aware scrollbars

libs/cli/src/generators/ui/supported-ui-libraries.json
This modifies the CLI
Closes #378
=> fix(nx): remove "helm" entry from suported-ui-libraries

CONTRIBUTING.md
I think this was left behind in #391 and confused me in the beginning :D
=> docs: replace pnpm with bun on CONTRIBUTING.md

apps/app/src/app/pages/(components)/components/(pagination)/pagination--advanced.example.ts, apps/app/src/app/pages/(components)/components/(pagination)/pagination.page.ts, libs/cli/src/generators/ui/libs/ui-pagination-helm/files/index.ts.template, libs/cli/src/generators/ui/libs/ui-pagination-helm/files/lib/hlm-numbered-pagination.component.ts.template, libs/ui/pagination/helm/src/index.ts, libs/ui/pagination/helm/src/lib/hlm-numbered-pagination.component.ts
=> feat(pagination): create advanced pagination

apps/app/src/app/shared/layout/side-nav/side-nav-content.component.ts
- [] Bugfix
The side nav has a menu item under UI for Dark Mode but the label is just "mode", which may confuse users. 
Closes #
I changed the label to "Dark Mode" to be more clear. 
- [ x] No
=> docs(ui): update link label to Dark Mode

apps/app/src/app/pages/(documentation)/documentation/changelog.page.ts, apps/app/src/app/pages/(documentation)/documentation/cli.page.ts, apps/app/src/app/pages/(documentation)/documentation/components-json.page.ts, apps/app/src/app/shared/layout/side-nav/side-nav-content.component.ts, libs/cli/src/generators/ui/generator.ts, libs/cli/src/generators/ui/schema.d.ts, libs/cli/src/generators/ui/schema.json, libs/cli/src/utils/config.ts
Heya, here's a naive implementation of a components.json storing a `componentsPath` to be used to install components without asking for the path each time.
Not particularly engineered, but does its job.
I'm new on the project so I might have missed some standards or common practices, feedback is welcome :)
Closes #355
=> feat: add config read/write to store components path

apps/app/src/app/pages/(components)/components/(pagination)/pagination--advanced.example.ts, apps/app/src/app/pages/(components)/components/(pagination)/pagination.page.ts, package.json
=> fix: fix linting errors in pagination

README.md, apps/app/src/app/pages/(home)/components/three-hundred.component.ts
Heyhey, can I become a spartan now? :D
=> docs: add Balastrong to the spartans list

libs/cli/src/generators/ui/libs/ui-aspect-ratio-helm/files/lib/helm-aspect-ratio.directive.ts.template, libs/ui/aspect-ratio/helm/src/lib/helm-aspect-ratio.directive.ts
=> refactor(aspect-ratio): migration to signals

libs/ui/separator/brain/src/lib/brn-separator.component.ts, libs/ui/separator/separator.stories.ts
Closes #440
- Covered areas: BrnSeparatorComponent
- Already using signals: HlmSeparatorDirective
=> refactor(separator): migration to signals

apps/app/src/app/pages/(components)/components/(select)/select.page.ts, apps/app/src/app/pages/(components)/components/(select)/select.preview.ts
#257 
#352 
Add the css import '@angular/cdk/overlay-prebuilt.css' (necessary for the component to function properly) in the documentation
=> docs(select): add missing css import

libs/cli/src/generators/ui/supported-ui-libraries.json, libs/ui/carousel/helm/package.json, package.json
Closes #
update the embla-carousel-angular to v18
=> chore(carousel): update embla-carousel-angular to v18

libs/ui/pagination/helm/src/lib/hlm-numbered-pagination.component.ts, libs/ui/pagination/helm/src/lib/hlm-pagination-content.directive.ts, libs/ui/pagination/helm/src/lib/hlm-pagination-ellipsis.component.ts, libs/ui/pagination/helm/src/lib/hlm-pagination-item.directive.ts, libs/ui/pagination/helm/src/lib/hlm-pagination-link.directive.ts, libs/ui/pagination/helm/src/lib/hlm-pagination-next.component.ts, libs/ui/pagination/helm/src/lib/hlm-pagination-previous.component.ts, libs/ui/pagination/helm/src/lib/hlm-pagination.directive.ts
Closes #424 
The pagination component was using signals, however I have updated it to follow the same conventions as we have used in other signal components, improved type safety and transforms etc..
I also removed a hard coded aria label as this would not be good for cases where localization is required.
=> refactor(pagination): migration to signals

libs/ui/sonner/helm/src/lib/hlm-toaster.component.ts
Closes #
Follow conventions for inputs and improve type safety for `class`
=> refactor(sonner): follow conventions and improve type safety

libs/ui/accordion/brain/src/lib/brn-accordion.directive.ts
=> refactor(accordion): remove triggers check, always defined as signal

apps/app/src/app/shared/input-error/input-error.directive.ts, libs/ui/label/brain/src/lib/brn-label.directive.ts, libs/ui/label/helm/src/lib/hlm-label.directive.ts, libs/ui/select/brain/src/lib/brn-select-label.directive.ts, libs/ui/select/brain/src/lib/brn-select.component.ts
=> refactor(label): migration to signals

libs/ui/alert/helm/src/lib/hlm-alert-description.directive.ts, libs/ui/alert/helm/src/lib/hlm-alert-title.directive.ts, libs/ui/alert/helm/src/lib/hlm-alert.directive.ts
=> refactor(alert): migrate to signals

apps/app/src/app/pages/(components)/components/(tooltip)/tooltip--simple.example.ts, apps/app/src/app/pages/(components)/components/(tooltip)/tooltip.page.ts, apps/app/src/app/pages/(components)/components/(tooltip)/tooltip.preview.ts
=> docs(tooltip): add simple string tooltip example

libs/ui/collapsible/brain/src/lib/brn-collapsible-content.component.ts, libs/ui/collapsible/brain/src/lib/brn-collapsible-trigger.directive.ts, libs/ui/collapsible/brain/src/lib/brn-collapsible.component.ts
Closes #
Closes [#435](https://github.com/spartan-ng/spartan/issues/435)
=> feat(collapsible)!: migrate collapsible to signals

libs/ui/avatar/brain/src/lib/brn-avatar.component.ts
=> fix(avatar): remove unused NgIf import

apps/app/src/app/pages/(components)/components/(dialog)/dialog.page.ts
#376 
Closes #376 
There is now a note in the Dynamic Component section of the Dialog documentation informing readers about this behavior.
=> docs(dialog): update docs for dialogs with dynamic content

libs/ui/sonner/helm/src/lib/hlm-toaster.component.ts
Closes #
Apply `toaster group` classes via `_computedClass`
=> refactor(sonner): apply class only once with computed

apps/app/drizzle.config.ts, apps/app/drizzle/0000_melted_weapon_omega.sql, apps/app/drizzle/meta/0000_snapshot.json, apps/app/drizzle/meta/_journal.json, apps/app/project.json, apps/app/src/app/pages/(stack)/stack/installation.page.ts, package.json, tools/scripts/drizzle-migrate.config.ts, vercel.json, zerops-import-example.yml, zerops.yml
Deployment config files are for deploying to vercel.
Migration is done manually.
Closes #416 
Scripts for Zerops are added.
Database migration via drizzle-kit was added and is used by the zerops configuration to automatically migrate the database. 
With the zerops-import-example.yml script you get a fully functional spartan.ng page on zerops (when this PR was merged). 
I added Zerops as provider in the installation page.
Should we change the drizzle documentation and add drizzle kit? 
Should we add more information about zerops?
=> ci: add zerops import and drizzle migrate, remove vercel

apps/app/src/app/pages/(components)/components/(pagination)/pagination--icon-only.example.ts, apps/app/src/app/pages/(components)/components/(pagination)/pagination--query-params.example.ts, apps/app/src/app/pages/(components)/components/(pagination)/pagination.page.ts, libs/ui/pagination/helm/src/lib/hlm-pagination-next.component.ts, libs/ui/pagination/helm/src/lib/hlm-pagination-previous.component.ts
Closes #
- new `iconOnly` input for `hlm-pagination-previous`/`hlm-pagination-next`
- add `queryParams`/`queryParamsHandling` to `hlm-pagination-previous`/`hlm-pagination-next`
- two new examples with Icon Only and Query params
=> Pagination icon only and query params

libs/brain/toggle/src/lib/brn-toggle.directive.spec.ts, libs/brain/toggle/src/lib/brn-toggle.directive.ts
=> fix(toggle): id binding (#527)

apps/app/src/app/pages/(components)/components/(dialog)/dialog-close.preview.ts, apps/app/src/app/pages/(components)/components/(dialog)/dialog.page.ts, apps/app/src/app/pages/(components)/components/(sheet)/sheet-close.preview.ts, apps/app/src/app/pages/(components)/components/(sheet)/sheet.page.ts
Closes #520/#509
There is now a dialog/sheet documentation section that describes different ways to close a dialog or sheet.
=> docs(dialog/sheet): add close dialog/sheet example

libs/cli/src/generators/ui/libs/ui-dialog-helm/files/lib/hlm-dialog.component.ts.template, libs/ui/dialog/helm/src/lib/hlm-dialog.component.ts
=> refactor(dialog): removed unused import

apps/app/src/app/pages/(documentation)/documentation/(ui)/figma.page.ts, apps/app/src/app/pages/(documentation)/documentation/(ui)/health-checks.page.ts, apps/app/src/app/pages/(documentation)/documentation/cli.page.ts, apps/app/src/app/pages/(home).page.ts, apps/app/src/app/shared/layout/side-nav/side-nav-content.component.ts, libs/cli/generators.json, libs/cli/jest.config.ts, libs/cli/package.json, libs/cli/src/generators/healthcheck/compat.ts, libs/cli/src/generators/healthcheck/generator.spec.ts, libs/cli/src/generators/healthcheck/generator.ts, libs/cli/src/generators/healthcheck/healthchecks.ts, libs/cli/src/generators/healthcheck/healthchecks/brain-imports.ts, libs/cli/src/generators/healthcheck/healthchecks/core-imports.ts, libs/cli/src/generators/healthcheck/healthchecks/hlm-icon.ts, libs/cli/src/generators/healthcheck/healthchecks/hlm-scroll-area.ts, libs/cli/src/generators/healthcheck/healthchecks/version.ts, libs/cli/src/generators/healthcheck/schema.d.ts, libs/cli/src/generators/healthcheck/schema.json, libs/cli/src/generators/healthcheck/utils/prompt.ts, libs/cli/src/generators/healthcheck/utils/reporter.ts, libs/cli/src/generators/healthcheck/utils/runner.ts, package.json, pnpm-lock.yaml
N/A
Adds a CLI health check tool (and documentation) that allows us to access the health of the project and automatically apply fixes for any outstanding issues.
This currently runs existing migrations, but we can extend it out to update components etc as well.
=> feat: cli healthcheck tool

apps/app/src/app/pages/(components)/components/(data-table)/data-table.page.ts
=> docs(data-table): fix Angular CLI install command

apps/ui-storybook-e2e/src/integration/carousel/carousel.cy.ts, apps/ui-storybook-e2e/src/integration/combobox/combobox.cy.ts
closes #386
re-enabling tests
Closes #386
=> test: re-enable combobox and carousel e2e tests

libs/brain/select/src/lib/brn-select.component.ts, libs/brain/select/src/lib/brn-select.service.ts, libs/brain/select/src/lib/tests/select-multi-mode.spec.ts, libs/brain/select/src/lib/tests/select-reactive-form.ts, libs/ui/select/select.stories.ts
=> fix(select): select dynamic options

libs/ui/date-picker/helm/package.json
=> fix(date-picker): peerDeps lint issue

apps/app/src/app/pages/(documentation)/documentation/(ui)/figma.page.ts, apps/app/src/app/pages/(documentation)/documentation/(ui)/health-checks.page.ts, apps/app/src/app/pages/(documentation)/documentation/(ui)/theming.page.ts
=> docs(repo): fix typos and improve grammar

libs/brain/select/src/lib/brn-select.component.ts, libs/brain/select/src/lib/tests/brn-select.component.spec.ts, libs/ui/select/select.stories.ts
Closes #412 
Adds a valueChange output to listen to select value changes
=> feat(select): add valueChange output

apps/ui-storybook-e2e/src/integration/select/select.cy.ts, libs/tools/generators.json, libs/tools/package.json, libs/tools/src/generators/helm-component/files/hlm-__fileName__.component.ts.template, libs/tools/src/generators/helm-component/generator.ts, libs/tools/src/generators/helm-component/schema.d.ts, libs/tools/src/generators/helm-component/schema.json, libs/tools/src/generators/helm-directive/files/hlm-__fileName__.directive.ts.template, libs/tools/src/generators/helm-directive/generator.ts, libs/tools/src/generators/helm-directive/schema.d.ts, libs/tools/src/generators/helm-directive/schema.json, libs/tools/src/generators/helm-documentation/files/(__fileName__)/__fileName__.page.ts.template, libs/tools/src/generators/helm-documentation/files/(__fileName__)/__fileName__.preview.ts.template, libs/tools/src/generators/helm-documentation/generator.ts, libs/tools/src/generators/helm-documentation/schema.d.ts, libs/tools/src/generators/helm-documentation/schema.json, libs/tools/src/generators/helm-library/generator.ts, libs/tools/src/generators/helm-library/schema.d.ts, libs/tools/src/generators/helm-library/schema.json, libs/tools/src/generators/helm-story/files/__fileName__.stories.ts.template, libs/tools/src/generators/helm-story/generator.ts, libs/tools/src/generators/helm-story/schema.d.ts, libs/tools/src/generators/helm-story/schema.json, libs/tools/src/generators/utils/ast.ts, package.json, pnpm-lock.yaml
Adding several new generators to automate the process of creating additional helm libraries, components, directives etc.. Its often hard for contributors to remember to set up everything when creating something, this should help automate that and ensure things are consistent.
If there are any steps you think we should add or anything I have missed, let me know and I can add it.
=> feat: helm generators

apps/app/src/app/pages/(components)/components/(data-table)/data-table.preview.ts, apps/app/src/app/pages/(examples)/examples/tasks/services/tasks.service.ts, apps/app/src/app/shared/input-error/input-error.directive.ts, libs/brain/calendar/src/lib/brn-calendar-week.directive.ts, libs/brain/collapsible/src/lib/brn-collapsible-content.component.ts, libs/brain/hover-card/src/lib/brn-hover-card-content.service.ts, libs/brain/slider/src/lib/brn-slider-track.directive.ts, libs/brain/table/src/lib/brn-paginator.directive.ts, libs/brain/tabs/src/lib/brn-tabs-trigger.directive.ts, libs/brain/tooltip/src/lib/brn-tooltip-trigger.directive.ts, libs/cli/src/generators/ui/libs/ui-accordion-helm/files/lib/hlm-accordion-content.component.ts.template, libs/cli/src/generators/ui/libs/ui-input-helm/files/lib/hlm-input.directive.ts.template, libs/cli/src/generators/ui/libs/ui-table-helm/files/lib/hlm-caption.component.ts.template, libs/cli/src/generators/ui/libs/ui-table-helm/files/lib/hlm-table.component.ts.template, libs/ui/accordion/helm/src/lib/hlm-accordion-content.component.ts, libs/ui/input/helm/src/lib/hlm-input.directive.ts, libs/ui/table/helm/src/lib/hlm-caption.component.ts, libs/ui/table/helm/src/lib/hlm-table.component.ts, libs/ui/table/table.stories.ts
Effects are written with allowSignalWrites, which was removed in Angular 19. 
Closes #602
Added untracked to all effects, also to ensure the effect is only triggered on the correct signals. 
fixed select e2e test by removing the error part, because the clear was removed in an earlier PR.
=> refactor: replace AllowSignalWrites with untracked

apps/app/src/app/pages/(stack)/stack/installation.page.ts
The command to install Supabase CLI tool with brew is not correct according to the Supabase documentation:
[Installing the Supabase CLI](https://supabase.com/docs/guides/local-development/cli/getting-started#installing-the-supabase-cli)
Documentation suggest using the following command for installing supabase:
```brew install supabase```
Closes #
Documentation suggest using the following command for installing supabase:
```brew install supabase/tap/supabase```
=> docs: update supabase installation command

apps/app/src/app/pages/(components)/components/(progress)/progress.preview.ts
Now the Progress code examples do not have `HlmProgressDirective‘ on `brn-progress’, so it doesn't work properly.
Closes #569
Now Progress code examples have complete template to copy by adding `HlmProgressDirective` on `brn-progress`. 
I have also added a new initial value for the Progress preview for a better Progress animation look.
=> docs(progress): add missing hlm & change initial value

apps/app/src/app/pages/(documentation)/documentation/(ui)/health-checks.page.ts, apps/app/src/app/pages/(documentation)/documentation/(ui)/update-guide.page.ts, apps/app/src/app/shared/layout/side-nav/side-nav-content.component.ts, libs/cli/generators.json, libs/cli/package.json, libs/cli/src/generators/base/generator.ts, libs/cli/src/generators/healthcheck/compat.ts, libs/cli/src/generators/healthcheck/generator.ts, libs/cli/src/generators/healthcheck/healthchecks.ts, libs/cli/src/generators/migrate-helm-libraries/compat.ts, libs/cli/src/generators/migrate-helm-libraries/generator.ts, libs/cli/src/generators/migrate-helm-libraries/schema.d.ts, libs/cli/src/generators/migrate-helm-libraries/schema.json, libs/cli/src/generators/ui/add-dependent-primitive.ts, libs/cli/src/generators/ui/generator.ts, libs/cli/src/utils/tsconfig.ts, libs/cli/tsconfig.spec.json, libs/tools/eslint.config.cjs
Closes #
Adding tooling to automate the updating of Helm libraries. This detects and removes the old one and regenerates them with the latest code. This is available as part of our existing health check command.
I have also added documentation for how to update the libraries to the latest version.
=> feat: adding helm library update tooling

libs/ui/sonner/helm/package.json
Closes #642, #536
This was intended to have been done as part of the Angular 19 changes - I updated the package but forgot the peer dependency.
=> chore: bump sonner

apps/app/src/app/pages/(components)/components/(date-picker)/date-picker--form.example.ts, apps/app/src/app/pages/(components)/components/(date-picker)/date-picker.page.ts, apps/app/src/app/pages/(components)/components/(date-picker)/date-picker.preview.ts, libs/brain/dialog/src/lib/brn-dialog.component.ts, libs/cli/src/generators/ui/libs/ui-date-picker-helm/files/lib/hlm-date-picker.component.ts.template, libs/cli/src/generators/ui/libs/ui-date-picker-helm/files/lib/hlm-date-picker.token.ts.template, libs/ui/date-picker/helm/src/lib/hlm-date-picker.component.ts, libs/ui/date-picker/helm/src/lib/hlm-date-picker.token.ts
=> feat(date-picker): autoCloseOnSelect option and open/close programmatically 

libs/brain/hlm-tailwind-preset.css
The progress indeterminate won't work with tailwind v4
Correct the custom animation class name base on Tailwind instruction
https://tailwindcss.com/docs/animation#customizing-your-theme
=> fix(progress): correct indeterminate animation class

apps/app/src/app/pages/(components)/components/(calendar)/calendar--multiple.example.ts, apps/app/src/app/pages/(components)/components/(calendar)/calendar.page.ts, apps/app/src/app/pages/(components)/components/(date-picker)/date-picker--form-multi.example.ts, apps/app/src/app/pages/(components)/components/(date-picker)/date-picker--form.example.ts, apps/app/src/app/pages/(components)/components/(date-picker)/date-picker--multi.example.ts, apps/app/src/app/pages/(components)/components/(date-picker)/date-picker.page.ts, libs/brain/calendar/src/index.ts, libs/brain/calendar/src/lib/brn-calendar-cell-button.directive.ts, libs/brain/calendar/src/lib/brn-calendar.directive.ts, libs/brain/calendar/src/lib/brn-calendar.token.ts, libs/brain/calendar/src/lib/mode/brn-calendar-multiple.directive.ts, libs/ui/calendar/helm/src/index.ts, libs/ui/calendar/helm/src/lib/hlm-calendar-multi.component.ts, libs/ui/calendar/helm/src/lib/hlm-calendar.component.ts, libs/ui/date-picker/helm/src/index.ts, libs/ui/date-picker/helm/src/lib/hlm-date-picker-multi.component.ts, libs/ui/date-picker/helm/src/lib/hlm-date-picker-multi.token.ts
Calendar single selection
* deselecting current date not supported
Calendar single selection
* deselect current date
Calendar multiple selection
* new `brnCalendarMulti` directive and `hlm-calendar-multi`component
* add `minSelection` and `maxSelection` inputs to limit deselection and reset selection when max reached
Date Picker multiple selection
* new `hlm-date-picker-multi`
* `autoCloseOnMaxSelection` option to close when `maxSelection` is reached
replaces #652
=> feat: calendar/date-picker multi selection

libs/brain/select/src/lib/brn-select-value.component.ts, libs/brain/select/src/lib/tests/brn-select.component.spec.ts, libs/ui/select/helm/src/lib/hlm-select-trigger.component.ts, libs/ui/select/helm/src/lib/hlm-select-value.directive.ts
=> fix(select): correcting placeholder color

libs/brain/slider/src/lib/brn-slider-thumb.directive.ts
Closes #658
Using pointer events instead of mouse events to ensure this works on touch devices. I also fixed a flickering issue when SSR is used.
=> fix(slider): ensure dragging works on touch devices

apps/app/src/app/pages/(components)/components/(date-picker)/date-picker--config.example.ts, apps/app/src/app/pages/(components)/components/(date-picker)/date-picker--form-multi.example.ts, apps/app/src/app/pages/(components)/components/(date-picker)/date-picker--form.example.ts, apps/app/src/app/pages/(components)/components/(date-picker)/date-picker--format.example.ts, apps/app/src/app/pages/(components)/components/(date-picker)/date-picker.preview.ts
=> docs(date-picker): keep example code up-to-date

libs/brain/radio-group/src/lib/brn-radio-group.directive.ts, libs/brain/radio-group/src/lib/brn-radio.component.spec.ts, libs/brain/radio-group/src/lib/brn-radio.component.ts
=> fix(radio-group): form disabled state

apps/ui-storybook-e2e/src/integration/switch/switch.cy.ts, libs/brain/switch/src/lib/brn-switch-ng-model.spec.ts, libs/brain/switch/src/lib/brn-switch-thumb.component.ts, libs/brain/switch/src/lib/brn-switch.component.spec.ts, libs/brain/switch/src/lib/brn-switch.component.ts, libs/ui/switch/helm/src/lib/hlm-switch-ng-model.component.ignore.spec.ts, libs/ui/switch/switch.stories.ts
putting the role in the right place
association aria and data attributes with the container using native attributes (checked,required,disabled) on hidden input
here is where it gets fun:
identified issue where checked is not applied correctly and found this gem: https://github.com/angular/components/issues/26101 current approach uses preventDefault in toggle and breaks. this current version works but not if we click on the switch (background) and not the thumb what's even more fun: e2e tests pass because cypress clicks right in the middle where our thumb is.
open to suggestions and help!
fixes #648
What kind of change does this …
=> fix(switch): fix accessibility issues

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, apps/app/src/app/pages/(components)/components/(breadcrumb)/breadcrumb--custom-separator.example.ts, apps/app/src/app/pages/(components)/components/(breadcrumb)/breadcrumb.preview.ts, libs/ui/breadcrumb/breadcrumb.stories.ts
Closes #
In one of the examples, the `link` input was still being used with `href`, which silently fails during runtime. Renamed this.
Also, update the package names in the contributing doc and in this MR template.
=> docs: rename href to link for breadcrumb links

apps/app/src/app/pages/(components)/components/(breadcrumb)/breadcrumb.page.ts, apps/app/src/app/pages/(components)/components/(dialog)/dialog.page.ts, apps/app/src/app/pages/(components)/components/(pagination)/pagination.page.ts, apps/app/src/app/pages/(components)/components/(sheet)/sheet.page.ts, apps/app/src/app/pages/(components)/components/(spinner)/spinner.page.ts, apps/app/src/app/pages/(documentation)/documentation/components-json.page.ts
I removed multiple NG0955 warnings triggered by duplicated keys
Warnings are being displayed in the browser
Closes #
=> fix(documentation): Removing multiple NG0955 warnings

libs/brain/switch/src/lib/brn-switch.component.ts
removed ViewEncapsulation.None
improve comments for auto generated docs
added onTouched calls and touched output during toggle
Closes #
=> fix(switch): touched and improve docs

package.json
Closes #
Changing the console output style for e2e tests to help prevent the output from being cut off unexpectedly.
=> build: improve e2e logs

apps/ui-storybook-e2e/src/integration/select/select.cy.ts, libs/brain/select/src/lib/brn-select-content.component.ts
Closes #691 
Multi select keyboard functionality now works as expected
=> fix(select): keyboard value toggle

libs/brain/calendar/src/lib/brn-calendar-week.directive.ts, libs/brain/calendar/src/lib/brn-calendar-weekday.directive.ts
Weekdays don't render correctly if the rendering days are changed (due to various reasons, for example, `weekStartsOn`)
Weekdays will re-render if the rendering days change. The logic is similar to `BrnCalendarWeekDirective`.
=> fix(calendar): rendering weekdays should follow changes of rendering days

libs/cli/src/generators/healthcheck/healthchecks/brn-radio.ts
The healthcheck modifies the spartan component ``HlmRadioComponent``
Closes #704 
The healthcheck ignores all files that end with ``hlm-radio.component.ts``
=> fix: hlm-radio component is not modified by healthchecks

apps/app/src/app/pages/(components)/components/(input-otp)/input-otp--form.example.ts, apps/app/src/app/pages/(components)/components/(input-otp)/input-otp.preview.ts, apps/ui-storybook/stories/input-otp.stories.ts, libs/brain/input-otp/src/index.ts, libs/brain/input-otp/src/lib/brn-input-otp-slot.component.ts, libs/brain/input-otp/src/lib/brn-input-otp.component.ts, libs/helm/input-otp/src/index.ts, libs/helm/input-otp/src/lib/hlm-input-otp-slot.component.ts, libs/helm/input-otp/src/lib/hlm-input-otp.directive.ts
- add comments to inputs
- add [hlmInputOtp] as directive selector
- update code snippets
- export all imports
=> feat: input otp polishing

libs/cli/src/generators/migrate-helm-libraries/schema.json, libs/cli/src/generators/migrate-icon/schema.json, libs/cli/src/generators/migrate-radio/schema.json, libs/cli/src/generators/migrate-select/schema.json, libs/cli/src/generators/migrate-toggle-group/schema.json, libs/tools/src/executors/docs/generate-ui-docs/schema.json, libs/tools/src/generators/auto-increment-version/schema.json, libs/tools/src/generators/brain-secondary-entrypoint/schema.json, libs/tools/src/generators/helm-component/schema.json, libs/tools/src/generators/helm-directive/schema.json, libs/tools/src/generators/helm-documentation/schema.json, libs/tools/src/generators/helm-secondary-entrypoint/schema.json, libs/tools/src/generators/helm-story/schema.json, libs/tools/src/generators/replace-cli-version/schema.json
Closes #
This PR resolves issues where running the generators from Angular CLI fails due to it not being able to fetch the schema.
=> fix(cli): correcting schema

libs/helm/pagination/src/lib/hlm-pagination-content.directive.ts, libs/helm/pagination/src/lib/hlm-pagination-ellipsis.component.ts, libs/helm/pagination/src/lib/hlm-pagination-item.directive.ts, libs/helm/pagination/src/lib/hlm-pagination-link.directive.ts, libs/helm/pagination/src/lib/hlm-pagination-next.component.ts, libs/helm/pagination/src/lib/hlm-pagination-previous.component.ts
=> feat: pagination sr only text

libs/helm/command/src/lib/hlm-command-search-input.component.ts, libs/helm/command/src/lib/hlm-command-search.component.ts, libs/helm/command/src/lib/hlm-command.component.ts, libs/helm/select/src/lib/hlm-select-content.directive.ts
=> fix: classvalue typing inconsistencies

apps/app/src/app/pages/(components)/components/(spinner)/spinner--size.preview.ts, apps/app/src/app/pages/(components)/components/(spinner)/spinner.generated.ts, apps/app/src/app/pages/(components)/components/(spinner)/spinner.page.ts, apps/app/src/app/pages/(components)/components/(spinner)/spinner.preview.ts, apps/ui-storybook/stories/spinner.stories.ts, libs/helm/spinner/src/index.ts, libs/helm/spinner/src/lib/hlm-spinner.component.ts
- remove size variant and variant in general
- add `motion-safe:animate-spin` to stop animation for reduced motion
- add size example to the docs via tailwind classes
Removed size variant
=> feat: spinner polishing

libs/cli/src/generators/base/lib/initialize-angular-library.ts
Closes #783 
We no longer ship tests with our helm components, so adding a test setup is not required. This skips the test setup so we don't install jest in a project that may not be using it.
=> fix(cli): prevent jest being installed

libs/helm/command/src/lib/hlm-command-separator.ts
=> fix(command): apply display block height is otherwise not applied

libs/helm/dialog/src/lib/hlm-dialog.service.ts
- [] Docs have been added / updated (for bug fixes / features)
Taken from PR #762 
> Ensures options.context is an object before spreading its properties. This prevents potential type errors and ensures that the dialog service correctly handles context objects when opening dialogs.
> 
> fixes https://github.com/spartan-ng/spartan/issues/749
since it has been over 3 weeks, I closed the other PR and opened this one. 
Closes #749
=> fix(dialog): fix TS2698 in HlmDialogService

libs/helm/menu/src/lib/hlm-menu-item.ts
Closes #806 
Removing ng-icon class that is preventing color overriding.
=> fix(dropdown-menu): fix menu item icon color

apps/app/src/app.config.ts, apps/app/src/app/shared/code/code.ts, apps/app/src/utils/prerender-routes.ts, apps/app/vite.config.ts, package.json, pnpm-lock.yaml
=> chore: bump analogjs + peer deps

libs/helm/alert/src/lib/hlm-alert.ts
Closes #828
Without an icon, there is no grid anymore. This works for the Theming page, which only uses a HlmAlertDescription.
=> fix(alert): add grid class only when icon is absent

apps/app/src/app/pages/(components)/components/(progress)/progress--indeterminate.preview.ts, apps/app/src/app/pages/(components)/components/(progress)/progress.preview.ts, apps/ui-storybook-e2e/src/integration/progress/progress.cy.ts, apps/ui-storybook/stories/progress.stories.ts, libs/brain/progress/src/lib/brn-progress-indicator.ts, libs/brain/progress/src/lib/brn-progress.ts, libs/cli/generators.json, libs/cli/src/generators/healthcheck/generator.ts, libs/cli/src/generators/healthcheck/healthchecks/hlm-progress.ts, libs/cli/src/generators/migrate-progress/compat.ts, libs/cli/src/generators/migrate-progress/generator.spec.ts, libs/cli/src/generators/migrate-progress/generator.ts, libs/cli/src/generators/migrate-progress/schema.d.ts, libs/cli/src/generators/migrate-progress/schema.json, libs/helm/progress/src/lib/hlm-progress-indicator.ts, libs/helm/progress/src/lib/hlm-progress.ts, libs/tools/src/executors/docs/generate-ui-docs/__snapshots__/executor.spec.ts.snap
Closes #
- Polishing progress docs
- As discussed on discord, hiding Brn imports where possible. Previously we had brain progress components, with helm directives, but this limits composability, so I have made the BrnProgress and BrnProgressIndicator components into directive so they can be used as hostDirectives. This allows only helm imports to be imported.
- Added healthcheck to perform migration.
=> refactor(progress): progress polish

apps/app/src/app/pages/(documentation)/documentation/(ui)/(typography)/typography.preview.ts
Importing hlmH1 instead of hlmH3
Closes #
Import hlmH3 instead of hlmH1
=> docs: import hlmH3 instead of hlmH1

apps/app/src/app/pages/(components)/components/(accordion)/accordion.preview.ts, libs/helm/accordion/src/lib/hlm-accordion-content.ts
The accordion content container was a `p` tag which don't work well with other elements like links etc.
Change the content container to `div` and update the preview.
=> feat: polish accordion content container

apps/app/src/app/pages/(components)/components/(command)/command--dialog.example.ts, apps/app/src/app/shared/header/header.ts, apps/app/src/styles.css, package.json, pnpm-lock.yaml
Add algolia docsearch to the site. Search can be opened via `CMD+K` (on Mac) and via the search bar/search icon in the header.
Styles inspired by Angular Primitives (cc @ashley-hunter)
=> docs: add docsearch to header

README.md, apps/app/src/app/pages/(home)/components/three-hundred.ts
=> docs: missing spartans

libs/tools/src/generators/helm-documentation/files/(__fileName__)/__fileName__.page.ts.template, libs/tools/src/generators/helm-documentation/generator.ts, libs/tools/src/generators/helm-secondary-entrypoint/generator.ts
Closes https://github.com/spartan-ng/spartan/issues/872
helm-documentation and helm-secondary-entrpoint follows the new Angular convention.
=> fix(cli): follow new Angular convention in helm-documentation and helm-secondary-entrypoint generators

apps/app/src/app/pages/(documentation)/documentation/components-json.page.ts, apps/app/src/app/pages/(documentation)/documentation/introduction.page.ts, libs/brain/accordion/src/lib/brn-accordion.ts
=> fix: accordion docs

apps/app/src/app/pages/(components)/components/(context-menu)/context-menu.preview.ts
=> fix: app import error

apps/app/index.html
=> docs: use correct type for favicon

.github/ISSUE_TEMPLATE/01-bug-report.yml, .github/ISSUE_TEMPLATE/02-feature-request.yml, .github/PULL_REQUEST_TEMPLATE.md, apps/app/src/app/core/models/primitives-snippets.model.ts, apps/app/src/app/pages/(components)/components/(input-otp)/input-otp.page.ts, apps/app/src/app/pages/(components)/components/(kbd)/kbd--button.preview.ts, apps/app/src/app/pages/(components)/components/(kbd)/kbd--group.preview.ts, apps/app/src/app/pages/(components)/components/(kbd)/kbd.page.ts, apps/app/src/app/pages/(components)/components/(kbd)/kbd.preview.ts, apps/app/src/app/pages/(components)/components/(label)/label.page.ts, apps/app/src/app/shared/layout/side-nav/side-nav-content.ts, apps/ui-storybook/stories/hlm-kbd.stories.ts, commitlint.config.cjs, libs/cli/src/generators/ui/libs/ui-kbd-helm/files/index.ts.template, libs/cli/src/generators/ui/libs/ui-kbd-helm/files/lib/hlm-kbd-group.ts.template, libs/cli/src/generators/ui/libs/ui-kbd-helm/files/lib/hlm-kbd.ts.template, libs/cli/src/generators/ui/libs/ui-kbd-helm/generator.ts, libs/cli/src/generators/ui/primitive-deps.ts, libs/cli/src/generators/ui/primitives.ts, libs/cli/src/generators/ui/supported-ui-libraries.json, libs/helm/kbd/README.md, libs/helm/kbd/ng-package.json, libs/helm/kbd/src/index.ts, libs/helm/kbd/src/lib/hlm-kbd-group.ts, libs/helm/kbd/src/lib/hlm-kbd.ts, libs/tools/src/executors/docs/generate-ui-docs/__snapshots__/executor.spec.ts.snap, tsconfig.base.json
=> feat(kbd): add kbd
